import { test, expect, type Page } from "@playwright/test"
import { readFile } from "node:fs/promises"

test.beforeEach(async ({ baseURL }) => {
  test.skip(process.env.CRM_BROWSER_LOCAL_WRITES !== "1" || baseURL !== "http://intake-upgrade-a.localhost:3001", "Requires the disposable local sales fixture.")
})
async function choose(page: Page, label: string, option: string) {
  await page.getByLabel(label, { exact: true }).click()
  await page.getByRole("menuitemradio", { name: option, exact: true }).click()
}

test("sales report drilldowns and downloads match source-filtered totals on desktop and mobile", async ({ page, request }, info) => {
  test.setTimeout(180000)
  expect((await request.patch("/api/modules", { data: { key: "realEstate", enabled: true } })).ok()).toBe(true)
  const suffix = Date.now(), sourceName = `Report source ${suffix}`
  const sourceResponse = await request.post("/api/crm/lead-sources", { data: { name: sourceName } })
  expect(sourceResponse.ok()).toBe(true)
  const source = await sourceResponse.json()
  const leadIds: string[] = []
  for (let i = 0; i < 2; i++) {
    const response = await request.post("/api/crm/enquiries", { data: { title: i ? `=SUM(1) Report ${suffix}` : `Report ${suffix}`, newContact: { name: `Report buyer ${suffix}-${i}` }, sourceId: source.id, assignedUserId: "intake_owner_a" } })
    expect(response.ok()).toBe(true); leadIds.push((await response.json()).id)
  }
  const lead = await (await request.get(`/api/crm/enquiries/${leadIds[0]}`)).json()
  const pipelineResponse = await request.post("/api/crm/pipelines", { data: { name: `Report pipeline ${suffix}`, stages: [
    { name: "Qualified", kind: "OPEN", probability: 25, color: "#123456" }, { name: "Won", kind: "WON", probability: 100, color: "#12ab34" }, { name: "Lost", kind: "LOST", probability: 0, color: "#ab1234" },
  ] } })
  expect(pipelineResponse.ok()).toBe(true)
  const pipeline = await pipelineResponse.json()
  const dealResponse = await request.post("/api/crm/opportunities", { data: { title: `Report deal ${suffix}`, contactId: lead.contactId, enquiryId: lead.id, enquiryVersion: lead.version, assignedUserId: "intake_owner_a", pipelineId: pipeline.id, stageId: pipeline.stages[0].id, amount: "100.1001", currency: "INR", expectedCloseOn: "2026-12-01" } })
  expect(dealResponse.ok()).toBe(true)
  const deal = await dealResponse.json()
  const report = await (await request.get(`/api/crm/reports/sales?sourceId=${source.id}`)).json()
  expect(report.totals).toMatchObject({ leads: 2, converted: 1, pipeline: 1, gaps: 1 })
  await page.goto("/crm/sales")
  await expect(page.getByRole("heading", { name: "Sales reports", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Filters", exact: true }).click()
  await page.getByLabel("Lead source", { exact: true }).click()
  await page.getByRole("option", { name: sourceName, exact: true }).click()
  await page.keyboard.press("Escape")
  const conversion = page.getByRole("region", { name: "Lead conversion", exact: true })
  await expect(conversion.getByRole("cell", { name: sourceName, exact: true })).toBeVisible()
  await expect(conversion.getByRole("button", { name: "2", exact: true })).toBeVisible()
  await conversion.getByRole("button", { name: "1", exact: true }).click()
  const records = page.getByRole("region", { name: "Converted leads", exact: true })
  await expect(records.locator(`a[href='/crm/enquiries/${lead.id}']`)).toBeVisible()
  const downloadPromise = page.waitForEvent("download")
  await records.getByRole("button", { name: "Export CSV" }).click()
  const download = await downloadPromise, path = info.outputPath(download.suggestedFilename())
  await download.saveAs(path)
  const csv = await readFile(path, "utf8")
  expect(csv).toContain(lead.id); expect(csv).not.toContain(leadIds[1])
  const response = await request.get(`/api/crm/reports/sales/export?sourceId=${source.id}`)
  expect(response.headers()["content-type"]).toContain("text/csv")
  expect(response.headers()["cache-control"]).toBe("no-store")
  expect(response.headers()["x-request-id"]).toBeTruthy()
  expect(await response.text()).toContain('"\'=SUM(1)')
  await page.getByRole("region", { name: "Deal values by stage" }).getByRole("button", { name: "1", exact: true }).click()
  await expect(page.getByRole("region", { name: "Open opportunities", exact: true }).locator(`a[href='/crm/opportunities/${deal.id}']`)).toBeVisible()
  await page.evaluate(() => { document.documentElement.classList.remove("dark") })
  await page.screenshot({ path: info.outputPath("sales-reports-desktop-light.png"), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => { document.documentElement.classList.add("dark") })
  await expect(page.locator("html")).toHaveClass(/dark/)
  await page.screenshot({ path: info.outputPath("sales-reports-mobile-dark.png"), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  await choose(page, "Report records", "Leads created")
  await expect(page.getByRole("region", { name: "Leads created", exact: true }).getByRole("link")).toHaveCount(2)
  await page.getByRole("button", { name: "Reporting period", exact: true }).click()
  await page.getByLabel("From", { exact: true }).fill("2020-01-01")
  await page.getByLabel("Through (inclusive)", { exact: true }).fill("2020-01-01")
  await page.getByRole("button", { name: "Apply period", exact: true }).click()
  await expect(conversion.getByText("No leads in this selection.")).toBeVisible()
  const historical = await (await request.get(`/api/crm/reports/sales?sourceId=${source.id}&from=2020-01-01&through=2020-01-01`)).json()
  expect(historical.totals).toMatchObject({ leads: 0, pipeline: 1, gaps: 1 })
  await page.goto("/crm/enquiries")
  await page.getByRole("textbox", { name: /Search title/ }).fill(`Report ${suffix}`)
  await expect(page.getByRole("link", { name: `Report ${suffix}`, exact: true })).toBeVisible()
  const leadDownload = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export CSV" }).click()
  const file = await leadDownload; await file.saveAs(info.outputPath("enquiries.csv"))
  expect(await readFile(info.outputPath("enquiries.csv"), "utf8")).toContain(leadIds[1])
  const opportunityCsv = await request.get(`/api/crm/opportunities/export?pipelineId=${pipeline.id}&page=99`)
  expect(opportunityCsv.ok()).toBe(true)
  expect(await opportunityCsv.text()).toContain(deal.id)
  await page.goto("/crm/opportunities")
  await page.getByLabel("Pipeline", { exact: true }).click()
  await page.getByRole("option", { name: pipeline.name, exact: true }).click()
  await expect(page.locator(`a[href='/crm/opportunities/${deal.id}']`)).toBeVisible()
  const dealDownload = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export CSV" }).click()
  const dealFile = await dealDownload; await dealFile.saveAs(info.outputPath("opportunities.csv"))
  expect(await readFile(info.outputPath("opportunities.csv"), "utf8")).toContain(deal.id)
})

test("failed report requests clear stale results and recover with Refresh", async ({ page }) => {
  await page.goto("/crm/sales")
  await expect(page.getByRole("region", { name: "Lead conversion" })).toBeVisible()
  await page.route("**/api/crm/reports/sales?*", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Report temporarily unavailable." }) }))
  await page.getByRole("button", { name: "Refresh", exact: true }).click()
  await expect(page.getByRole("alert").filter({ hasText: "Report temporarily unavailable." })).toBeVisible()
  await expect(page.getByRole("region", { name: "Lead conversion" })).toHaveCount(0)
  await page.unroute("**/api/crm/reports/sales?*")
  await page.getByRole("button", { name: "Refresh", exact: true }).click()
  await expect(page.getByRole("region", { name: "Lead conversion" })).toBeVisible()
})
