import { test, expect } from "@playwright/test"

test.beforeEach(async ({ baseURL }) => {
  test.skip(process.env.CRM_BROWSER_LOCAL_WRITES !== "1" || baseURL !== "http://intake-upgrade-a.localhost:3001", "Sales-team writes require the isolated local test business.")
})

test("configure team membership, enforce qualification and preserve the team in conversion", async ({ page, request }, info) => {
  test.setTimeout(180000)
  const name = `Qualification team ${Date.now()}`
  await page.goto("/crm/configuration/sales-teams")
  await page.getByRole("link", { name: "New sales team", exact: true }).click()
  await page.getByLabel("Team name", { exact: true }).fill(name)
  await page.getByRole("button", { name: "Save sales team", exact: true }).click()
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible()
  const id = page.url().split("/").at(-1)!
  await page.getByRole("combobox", { name: "Add salesperson", exact: true }).click()
  await page.getByRole("option", { name: "Local CRM Admin", exact: true }).click()
  await page.getByRole("button", { name: "Add member", exact: true }).click()
  await expect(page.getByRole("cell", { name: "Local CRM Admin", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("team-desktop.png"), fullPage: true })
  const assignees = await (await request.get("/api/crm/assignees")).json()
  const buyer = await (await request.post("/api/crm/contacts", { data: { name: `Team buyer ${Date.now()}` } })).json()
  await page.goto(`/crm/enquiries/new?contactId=${buyer.id}`)
  await page.getByLabel("Enquiry title", { exact: true }).fill("Team qualification enquiry")
  await page.getByRole("combobox", { name: "Sales team", exact: true }).click()
  await page.getByRole("option", { name, exact: true }).click()
  await expect(page.getByText(/Qualify enquiries first\. The salesperson/)).toBeVisible()
  await page.getByRole("button", { name: "Save enquiry", exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/enquiries\/(?!new)[^/]+$/)
  const leadId = page.url().split("/").at(-1)!
  const lead = await (await request.get(`/api/crm/enquiries/${leadId}`)).json()
  expect(lead.salesTeamId).toBe(id)
  const pipelineResponse = await request.post("/api/crm/pipelines", { data: { name: `Team pipeline ${Date.now()}`, stages: [{ name: "Qualified", kind: "OPEN", color: "#2563eb", probability: 10 }, { name: "Won", kind: "WON", color: "#00aa00", probability: 100 }, { name: "Lost", kind: "LOST", color: "#aa0000", probability: 0 }] } })
  expect(pipelineResponse.ok()).toBeTruthy()
  const pipeline = await pipelineResponse.json()
  const conversion = { title: lead.title, enquiryId: leadId, contactId: buyer.id, assignedUserId: assignees.currentUserId, pipelineId: pipeline.id, stageId: pipeline.stages[0].id, amount: "100", currency: "INR", expectedCloseOn: "2026-12-31" }
  expect((await request.post("/api/crm/opportunities", { data: conversion })).status()).toBe(400)
  await page.getByRole("button", { name: "Status", exact: true }).click()
  await page.getByRole("menuitemradio", { name: "QUALIFIED", exact: true }).click()
  await page.getByRole("button", { name: "Save enquiry", exact: true }).click()
  await expect.poll(async () => (await (await request.get(`/api/crm/enquiries/${leadId}`)).json()).status).toBe("QUALIFIED")
  await page.getByRole("link", { name: "Convert to opportunity", exact: true }).click()
  await expect(page.getByRole("combobox", { name: "Sales team", exact: true })).toContainText(name)
  await expect(page.getByRole("combobox", { name: "Sales team", exact: true })).toBeDisabled()
  await page.getByLabel("Expected close date", { exact: true }).fill("2026-12-31")
  await page.getByRole("button", { name: "Save opportunity", exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/opportunities\/(?!new)[^/?]+$/)
  await page.screenshot({ path: info.outputPath("team-conversion.png"), fullPage: true })
  const exported = await request.get(`/api/crm/opportunities/export?salesTeamId=${id}`)
  expect(exported.ok()).toBeTruthy(); expect(await exported.text()).toContain(name)
})

test("presets require preview and keep existing configuration on mobile", async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/crm/configuration/presets")
  await page.getByRole("button", { name: "Preset", exact: true }).click()
  await page.getByRole("menuitemradio", { name: "General sales", exact: true }).click()
  await expect(page.getByRole("button", { name: "Apply missing settings", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Preview changes", exact: true }).click()
  await expect(page.getByRole("heading", { name: /General sales — version/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("preset-mobile-preview.png"), fullPage: true })
  if (await page.getByRole("button", { name: "Apply missing settings", exact: true }).isEnabled()) {
    await page.getByRole("button", { name: "Apply missing settings", exact: true }).click()
    await expect(page.getByRole("status")).toContainText("Preset applied")
  }
  await expect(page.getByRole("cell", { name: "Keep existing", exact: true })).toHaveCount(4)
  await expect(page.getByRole("button", { name: "Apply missing settings", exact: true })).toBeDisabled()
  await page.goto("/crm/configuration/sales-teams")
  await expect(page.getByRole("heading", { name: "Sales teams", exact: true })).toBeVisible()
  await expect(page.getByRole("navigation", { name: "Pagination", exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await expect(page.getByRole("link", { name: /^Qualification team/ }).first()).toBeVisible()
  await page.screenshot({ path: info.outputPath("teams-mobile-list.png"), fullPage: true })
})

test("team-specific fields follow team selection without stale values", async ({ page, request }, info) => {
  const suffix = Date.now(), name = `Field team ${suffix}`, label = `Team requirement ${suffix}`
  const team = await (await request.post("/api/crm/sales-teams", { data: { name } })).json()
  const owner = (await (await request.get("/api/crm/assignees")).json()).currentUserId
  expect((await request.post(`/api/crm/sales-teams/${team.id}/members`, { data: { userId: owner, version: team.version } })).ok()).toBe(true)
  await page.goto("/crm/configuration/custom-fields/new")
  await page.getByLabel("Name", { exact: true }).fill(label)
  await page.getByLabel("Field code", { exact: true }).fill(`team_${suffix}`)
  await page.getByRole("combobox", { name: "Sales team", exact: true }).click()
  await page.getByRole("option", { name, exact: true }).click()
  await page.getByRole("button", { name: "Save field", exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/configuration\/custom-fields$/)
  await page.goto("/crm/enquiries/new")
  await expect(page.getByLabel(label, { exact: true })).toHaveCount(0)
  await page.getByRole("combobox", { name: "Sales team", exact: true }).click()
  await page.getByRole("option", { name, exact: true }).click()
  await expect(page.getByLabel(label, { exact: true })).toBeVisible()
  await page.getByLabel(label, { exact: true }).fill("Only this team's enquiry")
  await page.getByRole("button", { name: "Clear team", exact: true }).click()
  await expect(page.getByLabel(label, { exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("combobox", { name: "Sales team", exact: true }).click()
  await page.getByRole("option", { name, exact: true }).click()
  await expect(page.getByLabel(label, { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("team-fields-mobile.png"), fullPage: true })
})
