import { test, expect } from "@playwright/test"

test.beforeEach(async ({ baseURL }) => {
  test.skip(process.env.CRM_BROWSER_LOCAL_WRITES !== "1" || baseURL !== "http://intake-upgrade-a.localhost:3001", "Writes are restricted to the disposable local CRM fixture.")
})

test("configure a shared field, save it on an enquiry and preserve it through conversion", async ({ page, request }, info) => {
  const suffix = Date.now().toString(), name = `Preferred area ${suffix}`
  await page.goto("/crm/configuration/custom-fields")
  await expect(page.getByRole("heading", { name: "Custom fields", exact: true })).toBeVisible()
  await page.getByRole("link", { name: "New field", exact: true }).click()
  await page.getByLabel("Name", { exact: true }).fill(name)
  await page.getByLabel("Field code", { exact: true }).fill(`area_${suffix}`)
  await page.getByLabel("Help text").fill("Preferred neighbourhood for the next discussion.")
  await page.getByLabel("Allow filtering").check()
  await page.getByRole("button", { name: "Save field", exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/configuration\/custom-fields$/)
  await expect(page.getByRole("link", { name, exact: true })).toBeVisible()
  const fieldsResponse = await request.get(`/api/crm/custom-fields?q=${encodeURIComponent(name)}`)
  expect(fieldsResponse.ok()).toBeTruthy()
  const field = (await fieldsResponse.json()).items.find((item: { name: string }) => item.name === name)
  const assignees = await (await request.get("/api/crm/assignees")).json()
  const contactResponse = await request.post("/api/crm/contacts", { data: { name: `Custom fields buyer ${suffix}` } })
  expect(contactResponse.ok()).toBeTruthy()
  const contact = await contactResponse.json()
  const leadResponse = await request.post("/api/crm/enquiries", { data: { title: `Field test ${suffix}`, contactId: contact.id, assignedUserId: assignees.currentUserId } })
  expect(leadResponse.ok()).toBeTruthy()
  const lead = await leadResponse.json()
  await page.goto(`/crm/enquiries/${lead.id}`)
  await expect(page.getByRole("heading", { name: "Additional information", exact: true })).toBeVisible()
  await page.getByLabel(name, { exact: true }).fill("Pune West")
  await page.getByRole("button", { name: "Save enquiry", exact: true }).click()
  await expect.poll(async () => (await (await request.get(`/api/crm/enquiries/${lead.id}`)).json()).customFields.find((item: { id: string }) => item.id === field.id)?.value).toBe("Pune West")
  await page.screenshot({ path: info.outputPath("custom-fields-enquiry.png"), fullPage: true })
  const pipelineResponse = await request.post("/api/crm/pipelines", { data: { name: `Field sales ${suffix}`, stages: [{ name: "Qualified", kind: "OPEN", color: "#2563eb", probability: 10 }, { name: "Won", kind: "WON", color: "#00aa00", probability: 100 }, { name: "Lost", kind: "LOST", color: "#aa0000", probability: 0 }] } })
  expect(pipelineResponse.ok()).toBeTruthy()
  const pipeline = await pipelineResponse.json()
  await page.getByRole("link", { name: "Convert to opportunity", exact: true }).click()
  await expect(page.getByLabel(name, { exact: true })).toHaveValue("Pune West")
  await expect(page.getByLabel(name, { exact: true })).toBeDisabled()
  await expect(page.getByText(/Enquiry-only fields remain on the original enquiry/)).toBeVisible()
  // Conversion uses the same API as the form; select a deterministic isolated pipeline.
  const convert = await request.post("/api/crm/opportunities", { data: { title: `Converted ${suffix}`, enquiryId: lead.id, contactId: contact.id, assignedUserId: assignees.currentUserId, pipelineId: pipeline.id, stageId: pipeline.stages[0].id, amount: "100", currency: "INR", expectedCloseOn: "2026-12-31" } })
  expect(convert.ok()).toBeTruthy()
  const deal = await convert.json()
  await page.goto(`/crm/opportunities/${deal.id}`)
  await expect(page.getByLabel(name, { exact: true })).toHaveValue("Pune West")
  const exported = await request.get(`/api/crm/opportunities/export?customFieldId=${field.id}&customFieldValue=Pune%20West`)
  expect(exported.ok()).toBeTruthy(); expect(await exported.text()).toContain("Pune West")
  await page.goto("/crm/enquiries")
  await page.getByRole("button", { name: /^Filters/ }).click()
  await page.getByRole("combobox", { name: "Custom field", exact: true }).click()
  await page.getByRole("option", { name, exact: true }).click()
  await page.getByLabel(name, { exact: true }).fill("Pune West")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("link", { name: lead.title, exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("custom-fields-filter.png"), fullPage: true })
})

test("single-select configuration and project fields fit mobile with centered pagination", async ({ page, request }, info) => {
  const suffix = Date.now().toString(), name = `Permit status ${suffix}`
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/crm/configuration/custom-fields/new")
  await page.getByLabel("Name", { exact: true }).fill(name)
  await page.getByLabel("Field code", { exact: true }).fill(`permit_${suffix}`)
  await page.getByRole("button", { name: "Applies to", exact: true }).click()
  await page.getByRole("menuitemradio", { name: "Projects", exact: true }).click()
  await page.getByRole("button", { name: "Type", exact: true }).click()
  await page.getByRole("menuitemradio", { name: "Single select", exact: true }).click()
  await page.getByRole("button", { name: "Add option", exact: true }).click()
  await page.getByLabel("Option 1", { exact: true }).fill("Approved")
  await page.getByRole("button", { name: "Add option", exact: true }).click()
  await page.getByLabel("Option 2", { exact: true }).fill("Pending")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("custom-fields-config-mobile.png"), fullPage: true })
  await page.getByRole("button", { name: "Save field", exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/configuration\/custom-fields$/)
  const fields = await (await request.get(`/api/crm/custom-fields?q=${encodeURIComponent(name)}`)).json()
  const field = await (await request.get(`/api/crm/custom-fields/${fields.items[0].id}`)).json()
  const response = await request.post("/api/real-estate/projects", { data: { name: `Custom project ${suffix}`, code: `CF-${suffix}`, customFields: { [field.id]: field.options[0].id } } })
  expect(response.ok()).toBeTruthy()
  const project = await response.json()
  await page.goto(`/crm/projects/${project.id}`)
  await page.getByRole("button", { name: "Edit additional information", exact: true }).click()
  await expect(page.getByRole("combobox", { name, exact: true })).toContainText("Approved")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("custom-fields-project-mobile.png"), fullPage: true })
  await page.goto("/crm/configuration/custom-fields")
  await expect(page.getByRole("link", { name, exact: true })).toBeVisible()
  await expect(page.getByRole("navigation", { name: "Pagination", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("custom-fields-list-mobile.png"), fullPage: true })
})
