import { test, expect, type Page } from "@playwright/test"
import { fixture, pattern } from "./workforce-fixtures"
async function choose(page: Page, name: string, value: string) {
  await page.getByRole("button", { name, exact: true }).click()
  await page.getByRole("menuitemradio", { name: value, exact: true }).click()
}

test("leave definitions open read-only; drafts preserve rules through discard and failed saves", async ({ page }) => {
  const { writes, state } = await fixture(page)
  await page.goto("/leaves/leave")
  await expect(page.getByRole("heading", { name: "Request rules" })).toBeVisible()
  await expect(page.getByRole("textbox")).toHaveCount(0)
  await page.getByRole("button", { name: "Edit details" }).click()
  await page.getByLabel("Leave name", { exact: true }).fill("Changed")
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.getByRole("button", { name: "Discard changes" }).click()
  expect(writes).toHaveLength(0)
  await page.getByRole("button", { name: "Edit details" }).click()
  await expect(page.getByLabel("Leave name", { exact: true })).toHaveValue("Annual leave")
  state.fail = true
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect(page.getByRole("dialog").getByRole("alert")).toHaveText("This configuration is in use.")
  state.fail = false
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  expect(writes[1].body).toMatchObject({ code: "AL", maxDaysPerRequest: 10, allowCarryForward: true, holidayBothSideAllowed: true, nonClubbableWithIds: [] })
})

test("leave groups retain selected staff and definition IDs on mobile edits", async ({ page }) => {
  const { writes } = await fixture(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/leaves/groups/group")
  await page.getByRole("button", { name: "Edit details" }).click()
  await page.getByLabel("Group name", { exact: true }).fill("Updated team")
  await expect(page.locator("select:visible")).toHaveCount(0)
  await expect(page.getByLabel("Sam", { exact: true })).toBeChecked()
  const save = page.getByRole("button", { name: "Save changes", exact: true })
  const b = await save.boundingBox(); expect(b!.y + b!.height).toBeLessThanOrEqual(844)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath("leave-group-mobile.png"), animations: "disabled" })
  await save.click()
  await expect.poll(() => writes.length).toBe(1)
  expect(writes[0].body).toMatchObject({ staffIds: ["staff"], leaveDefinitionIds: ["leave"], description: "Saved group notes", assignmentMode: "SELECTED_STAFF" })
})

test("leave requests submit, display shared history and confirm cancellation", async ({ page }) => {
  const { writes } = await fixture(page)
  await page.goto("/leaves/requests")
  await page.getByRole("button", { name: "Apply leave", exact: true }).click()
  await page.getByLabel("Leave type", { exact: true }).click()
  await page.getByRole("option", { name: "AL - Annual leave", exact: true }).click()
  await page.getByRole("dialog").getByLabel("Start date", { exact: true }).fill("2030-10-07")
  await page.getByLabel("End date", { exact: true }).fill("2030-10-08")
  await page.getByLabel("Reason", { exact: true }).fill("Family trip")
  await page.getByRole("button", { name: "Submit request", exact: true }).click()
  await expect.poll(() => writes.length).toBe(1)
  expect(writes[0].body).toMatchObject({ leaveDefinitionId: "leave", startDate: "2030-10-07", endDate: "2030-10-08", reason: "Family trip" })
  await page.getByRole("button", { name: "Record actions" }).click()
  await page.getByRole("menuitem", { name: "View details" }).click()
  await expect(page.getByRole("list", { name: "Timeline entries" })).toBeVisible()
  await expect(page.getByText("Notice requirement met.")).toBeVisible()
  await page.getByRole("button", { name: "Close", exact: true }).first().click()
  await page.getByRole("button", { name: "Record actions" }).click()
  await page.getByRole("menuitem", { name: "Cancel request" }).click()
  expect(writes).toHaveLength(1)
  await page.getByLabel("Cancel reason (optional)").fill("Plans changed")
  await page.getByRole("button", { name: "Cancel request", exact: true }).click()
  await expect.poll(() => writes.length).toBe(2)
  expect(writes[1]).toMatchObject({ path: "/api/leaves/requests/request/cancel", body: { cancelReason: "Plans changed" } })
})

test("approval conflicts remain explicit and rejection retains its reason", async ({ page }) => {
  const { writes, state } = await fixture(page); state.conflict = true
  await page.goto("/leaves/approvals")
  await page.getByRole("button", { name: "Record actions" }).click()
  await page.getByRole("menuitem", { name: "Approve", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Conflicting appointments found" })).toBeVisible()
  expect(writes).toHaveLength(1)
  await page.getByRole("button", { name: "Close", exact: true }).first().click()
  state.conflict = false
  await page.getByRole("button", { name: "Record actions" }).click()
  await page.getByRole("menuitem", { name: "Reject", exact: true }).click()
  await page.getByLabel("Comment", { exact: true }).fill("Please choose another date")
  await page.getByRole("button", { name: "Reject", exact: true }).click()
  await expect.poll(() => writes.length).toBe(2)
  expect(writes[1].body).toMatchObject({ status: "REJECTED", reviewerComment: "Please choose another date" })
})

test("shift templates separate views and edits and preserve time and break payloads", async ({ page }) => {
  const { writes, queries } = await fixture(page)
  await page.goto("/shifts")
  await page.getByRole("button", { name: "Next page" }).click()
  await expect(page.getByText("Page 2 of 3", { exact: true })).toBeVisible()
  await choose(page, "All statuses", "Active")
  await expect.poll(() => queries.filter(url => url.pathname === "/api/shifts/templates").at(-1)?.searchParams.get("page")).toBe("1")
  await page.getByRole("button", { name: "Day shift", exact: true }).click()
  await expect(page.getByRole("dialog").getByRole("textbox")).toHaveCount(0)
  await page.getByRole("button", { name: "Edit details" }).click()
  await page.getByLabel("Name", { exact: true }).fill("Updated day shift")
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect.poll(() => writes.length).toBe(1)
  expect(writes[0].body).toMatchObject({ name: "Updated day shift", startTime: "09:00", endTime: "17:00", breaks: [{ startTime: "12:00", endTime: "13:00", sortOrder: 0 }] })
  await page.screenshot({ path: test.info().outputPath("shifts-desktop.png"), animations: "disabled" })
})

test("schedule edits preserve assignments, repeating blocks and alternate week-off rules", async ({ page }) => {
  const { writes } = await fixture(page)
  await page.goto("/shifts/schedules")
  await page.getByRole("button", { name: "Record actions" }).click()
  await page.getByRole("menuitem", { name: "View details" }).click()
  await expect(page.getByRole("heading", { name: "Staff assignments" })).toBeVisible()
  await page.getByRole("button", { name: "Edit details" }).click()
  await page.getByLabel("Schedule name", { exact: true }).fill("Updated schedule")
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect.poll(() => writes.length).toBe(1)
  expect(writes[0].body).toMatchObject({ name: "Updated schedule", staffIds: ["staff"], weekOffDay1: "SUNDAY", weekOffDay2: "SATURDAY", weekOff2Weeks: [2, 4], blocks: [{ templateId: "template", repeatDays: 5 }] })
})

test("recurring plans keep view and draft separate and preserve weekly availability", async ({ page }) => {
  const { writes } = await fixture(page)
  await page.goto("/shifts/recurring")
  await page.getByRole("button", { name: "Flexible mornings", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Pattern details" })).toBeVisible()
  await page.getByRole("button", { name: "Edit details" }).click()
  await page.getByLabel("Pattern name", { exact: true }).fill("Changed mornings")
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.getByRole("button", { name: "Discard changes" }).click()
  expect(writes.filter(write => !write.path.endsWith("impact-preview"))).toHaveLength(0)
  await page.getByRole("button", { name: "Flexible mornings", exact: true }).click()
  await page.getByRole("button", { name: "Edit details" }).click()
  await expect(page.getByLabel("Pattern name", { exact: true })).toHaveValue("Flexible mornings")
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect.poll(() => writes.some(write => write.method === "PUT")).toBe(true)
  const write = writes.find(write => write.method === "PUT")!
  expect(write.body).toMatchObject({ staffId: "flex", cycleLengthWeeks: 1, name: "Flexible mornings", weeks: [{ weekIndex: 1, days: [{ day: "MONDAY", isOff: false, slots: [{ startTime: "09:00", endTime: "12:00", breaks: [] }] }, ...pattern.weeks[0].days.slice(1).map(day => ({ day: day.day, isOff: true, slots: [] }))] }] })
})

test("roster grid stays within the mobile layout and weekly navigation remains available", async ({ page }) => {
  await fixture(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/shifts/roster")
  await expect(page.getByRole("heading", { name: "Roster", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Next week" })).toBeVisible()
  await page.getByRole("button", { name: "Next week" }).click()
  await expect(page.getByText("Sam", { exact: true }).first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath("roster-mobile.png"), animations: "disabled" })
})

test("new leave definitions and groups retain drafts on failure and submit configured rules", async ({ page }) => {
  const { writes, state } = await fixture(page)
  await page.goto("/leaves/new")
  await page.getByLabel("Leave code", { exact: true }).fill("CL")
  await page.getByLabel("Leave name", { exact: true }).fill("Casual leave")
  state.fail = true
  await page.getByRole("button", { name: "Create leave definition", exact: true }).click()
  await expect(page.getByRole("alert").filter({ hasText: "This configuration is in use." }).first()).toBeVisible()
  await expect(page.getByLabel("Leave name", { exact: true })).toHaveValue("Casual leave")
  state.fail = false
  await page.getByRole("button", { name: "Create leave definition", exact: true }).click()
  await expect(page).toHaveURL(/\/leaves\/leave$/)
  expect(writes.at(-1)?.body).toMatchObject({ code: "CL", name: "Casual leave", leaveType: "PAID", maxPendingRequests: 3 })
  await page.goto("/leaves/groups/new")
  await page.getByLabel("Group code", { exact: true }).fill("SALES")
  await page.getByLabel("Group name", { exact: true }).fill("Sales team")
  await page.getByLabel("Leaves in this group", { exact: true }).click()
  await page.getByRole("option", { name: "AL - Annual leave", exact: true }).click()
  await page.keyboard.press("Escape")
  await page.getByLabel("Make this the default leave group").check()
  await page.getByRole("button", { name: "Create leave group", exact: true }).click()
  await expect(page).toHaveURL(/\/leaves\/groups\/group$/)
  expect(writes.at(-1)?.body).toMatchObject({ code: "SALES", name: "Sales team", leaveDefinitionIds: ["leave"], assignmentMode: "ALL_STAFF", staffIds: [] })
})

test("new shift drafts discard cleanly and schedule creation retains its template link", async ({ page }) => {
  const { writes } = await fixture(page)
  await page.goto("/shifts")
  await page.getByRole("button", { name: "New template", exact: true }).click()
  await page.getByLabel("Name", { exact: true }).fill("Discard this")
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.getByRole("button", { name: "Discard changes" }).click()
  await page.getByRole("button", { name: "New template", exact: true }).click()
  await expect(page.getByLabel("Name", { exact: true })).toHaveValue("")
  await page.getByLabel("Name", { exact: true }).fill("New day shift")
  await page.getByRole("button", { name: "Create template", exact: true }).click()
  await expect.poll(() => writes.length).toBe(1)
  expect(writes[0]).toMatchObject({ path: "/api/shifts/templates", method: "POST", body: { name: "New day shift", isActive: true } })
  await page.goto("/shifts/schedules")
  await page.getByRole("button", { name: "New schedule", exact: true }).click()
  await page.getByLabel("Schedule name", { exact: true }).fill("Discard schedule")
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.getByRole("button", { name: "Discard changes" }).click()
  await page.getByRole("button", { name: "New schedule", exact: true }).click()
  await expect(page.getByLabel("Schedule name", { exact: true })).toHaveValue("")
  await page.getByLabel("Schedule name", { exact: true }).fill("Default shift")
  await page.getByLabel("Make this the default schedule").check()
  await page.getByRole("dialog").getByLabel("Start date", { exact: true }).fill("2030-10-07")
  await page.getByLabel("Shift template 1", { exact: true }).click()
  await page.getByRole("option", { name: "Day shift", exact: true }).click()
  await page.getByRole("button", { name: "Create schedule", exact: true }).click()
  await expect.poll(() => writes.length).toBe(2)
  expect(writes[1]).toMatchObject({ path: "/api/shifts/schedules", method: "POST", body: { name: "Default shift", isDefault: true, staffIds: [], blocks: [{ templateId: "template", repeatDays: 1 }] } })
})

test("staff leave requests do not expose manager controls", async ({ page }) => {
  await fixture(page)
  await page.goto("/leaves/requests?role=STAFF")
  await expect(page.getByRole("button", { name: "Apply leave", exact: true })).toBeVisible()
  await expect(page.getByRole("link", { name: "Approvals", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Record actions" }).click()
  await expect(page.getByRole("menuitem", { name: "Approve", exact: true })).toHaveCount(0)
  await expect(page.getByRole("menuitem", { name: "Cancel request", exact: true })).toBeVisible()
})

test("roster override actions stay visible on mobile and save the selected unavailability", async ({ page }) => {
  const { writes } = await fixture(page)
  await page.route("**/api/shifts/overrides", async route => {
    if (route.request().method() === "GET") return route.fallback()
    writes.push({ path: "/api/shifts/overrides", method: "POST", body: route.request().postDataJSON() })
    return route.fulfill({ json: { createdCount: 1 } })
  })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/shifts/roster")
  await page.getByRole("button", { name: "Next week" }).click()
  await page.getByRole("row").filter({ has: page.getByText("Sam", { exact: true }) }).getByRole("cell", { name: "Off", exact: true }).first().click()
  await expect(page.getByRole("heading", { name: "Change shift", exact: true })).toBeVisible()
  await page.getByLabel("Mark as unavailable", { exact: true }).check()
  const save = page.getByRole("button", { name: "Save override", exact: true })
  const bounds = await save.boundingBox(); expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844)
  await page.screenshot({ path: test.info().outputPath("roster-override-mobile.png"), animations: "disabled" })
  await save.click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  expect(writes[0].body).toMatchObject({ staffId: "staff", isUnavailable: true, templateId: "", skipWeekOff: false, skipHolidays: false })
})

test("recurring creation configures weekly slots without submitting editor buttons", async ({ page }) => {
  const { writes } = await fixture(page)
  await page.goto("/shifts/recurring")
  await page.getByRole("button", { name: "New recurring plan", exact: true }).click()
  await choose(page, "Staff", "Flex Staff")
  await page.getByLabel("Pattern name", { exact: true }).fill("Monday availability")
  await page.getByLabel("Valid from", { exact: true }).fill("2030-10-07")
  await page.getByLabel("Off", { exact: true }).first().uncheck()
  expect(writes).toHaveLength(0)
  await page.getByRole("button", { name: "Create pattern", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  expect(writes[0]).toMatchObject({ method: "PUT", path: "/api/shifts/flexible-patterns", body: { staffId: "flex", name: "Monday availability", validFrom: "2030-10-07", weeks: [{ weekIndex: 1, days: [{ day: "MONDAY", isOff: false, slots: [{ startTime: "10:00", endTime: "14:00", breaks: [] }] }, ...pattern.weeks[0].days.slice(1).map(day => ({ day: day.day, isOff: true, slots: [] }))] }] } })
})
