import { test, expect, type Page } from "@playwright/test"

test.beforeEach(({ baseURL }) => { test.skip(baseURL !== "http://127.0.0.1:3012", "Only run against the isolated, intercepted component host.") })

async function fixture(page: Page, manager = true, subproject = false) {
  const custom = { id: "rera", scope: "PROJECT", code: "rera", name: "Registration", type: "TEXT", helpText: "", position: 1, required: false, archived: false, editable: true, filterable: false, maxLength: 100, minimum: null, maximum: null, defaultValue: null, value: "REG-001", options: [] }
  const project = { id: "test", name: "Green Meadows Test", code: "GM-TEST", location: "Pune", parentId: subproject ? "parent" : null, parent: subproject ? { id: "parent", name: "Green Meadows", archived: false } : null, developerAccountId: null, description: "Apartments and villas near the city.", categories: ["apartment", "villa"], categoryNames: { apartment: "Apartment", villa: "Villa" }, lifecycle: "planning", lifecycleName: "Pre launch", priceMin: "5000000", priceMax: "9000000", currency: "INR", archived: false, version: 3, canManage: manager, customFields: [custom] }
  const writes: { path: string; body: Record<string, unknown> }[] = [], reads: string[] = []
  let conflict = false
  await page.route("**/api/**", async route => {
    const req = route.request(), url = new URL(req.url()), path = url.pathname
    const list = { items: [], total: 0, page: 1, pageSize: 20, totalPages: 1, canManage: manager }
    if (req.method() !== "GET") {
      const body = req.postDataJSON(); writes.push({ path, body })
      if (conflict) return route.fulfill({ status: 409, json: { error: "This record changed. Refresh before saving." } })
      if (path.endsWith("/members")) return route.fulfill({ json: { version: ++project.version } })
      const customPatch = body.customFields
      Object.assign(project, body, { id: "test", version: project.version + 1, customFields: [{ ...custom, value: customPatch.rera ?? project.customFields[0].value }] })
      return route.fulfill({ json: project })
    }
    reads.push(req.url())
    if (path === "/api/real-estate/projects/test" || path === "/api/real-estate/projects/parent") return route.fulfill({ json: project })
    if (path === "/api/real-estate/choices/defaults") return route.fulfill({ json: { "project-statuses": { id: "planning", name: "Pre launch" } } })
    if (path === "/api/settings/display") return route.fulfill({ json: { settings: { currency: "INR", dateFormat: "dd/MM/yyyy", timeZone: "Asia/Kolkata" } } })
    if (path === "/api/crm/custom-fields/form/project") return route.fulfill({ json: [custom] })
    if (path === "/api/real-estate/choices/project-statuses") return route.fulfill({ json: { ...list, items: [{ id: "planning", name: "Pre launch" }] } })
    if (path === "/api/real-estate/choices/property-categories") return route.fulfill({ json: { ...list, items: [{ id: "apartment", name: "Apartment" }, { id: "villa", name: "Villa" }] } })
    return route.fulfill({ json: { ...list, timeZone: "Asia/Kolkata", canAssign: manager } })
  })
  return { writes, reads, project, setConflict: (value: boolean) => { conflict = value } }
}

test("read-only overview, lazy tabs, focused saves, discard and version conflicts", async ({ page }, info) => {
  const state = await fixture(page)
  await page.goto("/crm/projects/test")
  await expect(page.getByRole("heading", { name: "Green Meadows Test", exact: true })).toBeVisible()
  await expect(page.getByRole("textbox")).toHaveCount(0)
  expect(state.reads.some(url => /\/api\/crm\/(enquiries|opportunities|work)/.test(url))).toBe(false)
  await page.screenshot({ path: info.outputPath("overview-desktop.png"), fullPage: true })
  await page.getByRole("button", { name: "Edit details", exact: true }).click()
  await page.getByLabel("Location", { exact: true }).fill("Mumbai")
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.getByRole("button", { name: "Discard changes", exact: true }).click()
  expect(state.writes).toHaveLength(0)
  await page.getByRole("button", { name: "Edit details", exact: true }).click()
  await expect(page.getByLabel("Location", { exact: true })).toHaveValue("Pune")
  await page.getByLabel("Location", { exact: true }).fill("Mumbai")
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  expect(state.writes[0].body).toMatchObject({ location: "Mumbai", version: 3, categories: ["apartment", "villa"], priceMin: "5000000", customFields: {} })
  await page.getByRole("button", { name: "Edit additional information", exact: true }).click()
  await page.getByLabel("Registration", { exact: true }).fill("REG-002")
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByText("REG-002", { exact: true })).toBeVisible()
  await page.getByRole("tab", { name: "Subprojects", exact: true }).click()
  await expect(page.getByRole("link", { name: "New subproject", exact: true })).toHaveAttribute("href", "/crm/projects/new?parentId=test")
  await expect(page.getByText("No projects match this selection.")).toBeVisible()
  await expect(page.getByRole("navigation", { name: "Pagination" })).toHaveCount(0)
  await page.getByRole("tab", { name: "Sales", exact: true }).click()
  await expect(page.getByText("No enquiries found.")).toBeVisible()
  expect(state.reads.some(url => url.includes("/api/crm/enquiries?") && url.includes("projectId=test"))).toBe(true)
  await page.getByRole("tab", { name: "Activities", exact: true }).click()
  await expect.poll(() => state.reads.some(url => url.includes("/api/crm/work?") && url.includes("projectId=test"))).toBe(true)
  await page.getByRole("tab", { name: "Overview", exact: true }).click()
  state.setConflict(true)
  await page.getByRole("button", { name: "Edit pricing", exact: true }).click()
  await page.getByLabel("Indicative minimum price", { exact: true }).fill("5500000")
  await page.getByRole("button", { name: "Save changes", exact: true }).click()
  await expect(page.getByRole("alert")).toHaveText("This record changed. Refresh before saving.")
  await expect(page.getByLabel("Indicative minimum price", { exact: true })).toHaveValue("5500000")
})

test("mobile panel, keyboard tabs, archive confirmation and staff permissions", async ({ page }, info) => {
  const state = await fixture(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/crm/projects/test")
  await page.getByRole("tab", { name: "Overview", exact: true }).focus()
  await page.keyboard.press("ArrowRight")
  await expect(page.getByRole("tab", { name: "Subprojects", exact: true })).toBeFocused()
  await page.keyboard.press("Home")
  await page.screenshot({ path: info.outputPath("overview-mobile.png"), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.getByRole("button", { name: "Edit pricing", exact: true }).click()
  await expect(page.getByRole("button", { name: "Save changes", exact: true })).toBeInViewport()
  await expect.poll(async () => Math.round((await page.getByRole("dialog").boundingBox())!.x)).toBe(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("pricing-mobile.png"), fullPage: true })
  await page.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.getByRole("button", { name: "More actions", exact: true }).click()
  await page.getByRole("menuitem", { name: "Archive project", exact: true }).click()
  expect(state.writes).toHaveLength(0)
  await page.getByRole("button", { name: "Confirm and save", exact: true }).click()
  await expect(page.getByText("Archived", { exact: true })).toBeVisible()
  expect(state.writes[0].body.archived).toBe(true)
  await page.unroute("**/api/**")
  await fixture(page, false)
  await page.reload()
  await expect(page.getByRole("heading", { name: "Green Meadows Test", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: /^Edit / })).toHaveCount(0)
  await expect(page.getByRole("tab", { name: "Team", exact: true })).toHaveCount(0)
  await expect(page.getByRole("textbox")).toHaveCount(0)
})

test("creation defaults currency, preserves parent and opens the saved detail", async ({ page }, info) => {
  const state = await fixture(page)
  await page.goto("/crm/projects/new?parentId=parent")
  await expect(page.getByRole("heading", { name: "New subproject", exact: true })).toBeVisible()
  await page.getByLabel("Project name", { exact: true }).fill("Tower A")
  await page.getByLabel("Project code", { exact: true }).fill("GM-A")
  await expect(page.getByLabel("Currency code (e.g. INR)", { exact: true })).not.toBeVisible()
  await page.screenshot({ path: info.outputPath("create-desktop.png"), fullPage: true })
  await page.getByRole("button", { name: "Save project", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Tower A", exact: true })).toBeVisible()
  expect(state.writes[0].body).toMatchObject({ currency: "INR", parentId: "parent", name: "Tower A", code: "GM-A" })
  await expect(page.getByRole("tab", { name: "Subprojects", exact: true })).toHaveCount(0)
  await page.getByRole("tab", { name: "Team", exact: true }).click()
  await expect(page.getByText("Staff access is inherited from the parent project.")).toBeVisible()
})
