import fs from "node:fs"
import { test, expect } from "@playwright/test"
import { emptyQuotationContent } from "../../modules/sales-documents/quotation-validation"
test("quotation template, immutable versions, PDF and standard mobile controls", async ({ page, request, baseURL }, info) => {
  test.skip(process.env.CRM_BROWSER_LOCAL_WRITES !== "1" || baseURL !== "http://quotation-test.localhost:3001", "Writes require the isolated quotation test business.")
  test.setTimeout(240000)
  for (const key of ["crm", "salesDocuments", "paymentPlans", "realEstate"]) expect((await request.patch("/api/modules", { data: { key, enabled: true } })).ok()).toBeTruthy()
  const session = await (await request.get("/api/auth/session")).json()
  const contact = await (await request.post("/api/crm/contacts", { data: { name: "Quotation buyer" } })).json()
  const pipeline = await (await request.post("/api/crm/pipelines", { data: { name: `Quotation pipeline ${Date.now()}`, archived: false, stages: [{ name: "Qualified", kind: "OPEN", probability: 20, color: "#336699", archived: false }, { name: "Won", kind: "WON", probability: 100, color: "#339966", archived: false }, { name: "Lost", kind: "LOST", probability: 0, color: "#993333", archived: false }] } })).json()
  const response = await request.post("/api/crm/opportunities", { data: { title: "Plot 29 enquiry", contactId: contact.id, assignedUserId: session.user.id, pipelineId: pipeline.id, stageId: pipeline.stages[0].id, amount: "3705000", currency: "INR", expectedCloseOn: "2026-12-31" } })
  expect(response.ok()).toBeTruthy()
  const deal = await response.json()
  await page.goto("/crm/configuration/quotation-templates/new")
  const name = `Reference template ${Date.now()}`
  await page.getByLabel("Template name", { exact: true }).fill(name)
  await page.getByLabel("Business / developer name", { exact: true }).fill("Example Developer")
  await page.getByLabel("Description", { exact: true }).fill("Plot 29")
  await page.getByLabel("Quantity / area", { exact: true }).fill("247")
  await page.getByLabel("Unit", { exact: true }).fill("sq. m")
  await page.getByLabel("Rate per unit", { exact: true }).fill("15000")
  await page.getByRole("button", { name: "Save template", exact: true }).click()
  await expect(page).toHaveURL(/quotation-templates\/(?!new)[^/]+$/)
  const id = page.url().split("/").at(-1)!
  // Six-step client reference template, stored only in this disposable tenant.
  const template = await (await request.get(`/api/crm/quotation-templates/${id}`)).json()
  const content = { ...emptyQuotationContent, ...template.content, charges: [{ label: "Stamp duty", group: "Statutory", kind: "FIXED", value: "185300", included: false, basis: "BASE", due: "At registration" }, { label: "Registration", group: "Statutory", kind: "FIXED", value: "30000", included: false, basis: "BASE", due: "At registration" }], instalments: [10,10,25,25,20,10].map((n,i) => ({ label: `Payment ${i+1}`, percent: String(n), days: [0,30,90,170,220,300][i], note: "" })) }
  expect((await request.put(`/api/crm/quotation-templates/${id}`, { data: { name, version: template.version, content } })).ok()).toBeTruthy()
  await page.goto(`/crm/opportunities/${deal.id}`)
  await page.getByRole("link", { name: "New document", exact: true }).click()
  await page.getByRole("combobox", { name: "Template", exact: true }).click()
  await page.getByRole("option", { name, exact: true }).click()
  await page.getByRole("button", { name: "Apply template", exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Apply template", exact: true }).click()
  await expect(page.getByLabel("Quantity / area", { exact: true })).toHaveValue("247")
  await expect(page.getByRole("region", { name: "Calculated summary" })).toContainText("215,300")
  await page.getByLabel("Rate per unit", { exact: true }).fill("-")
  await page.getByRole("button", { name: "Save document", exact: true }).click()
  await expect(page.getByLabel("Rate per unit", { exact: true }).locator("..")).toContainText("Enter a positive number")
  await page.getByLabel("Rate per unit", { exact: true }).fill("15000")
  await page.getByLabel("Booking date (optional)", { exact: true }).fill("2026-09-23")
  await page.getByRole("button", { name: "Save document", exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/quotations\/(?!new)[^/?]+$/)
  const quotationId = page.url().split("/").at(-1)!
  await expect(page.getByRole("heading", { level: 1 })).toContainText("version 1")
  await page.screenshot({ path: info.outputPath("quotation-desktop.png"), fullPage: true })
  const pdf = await request.get(`/api/crm/quotations/${quotationId}/pdf?revision=1`)
  expect(pdf.status()).toBe(200); expect(pdf.headers()["content-type"]).toBe("application/pdf")
  expect((await pdf.body()).subarray(0,5).toString()).toBe("%PDF-")
  await page.getByLabel("Discount amount", { exact: true }).fill("5000")
  await page.getByRole("button", { name: "Save new version", exact: true }).click()
  await expect(page.getByRole("heading", { level: 1 })).toContainText("version 2")
  await page.getByRole("navigation", { name: "Document versions" }).getByRole("button", { name: "Previous page" }).click()
  await expect(page.getByLabel("Discount amount", { exact: true })).toHaveValue("0")
  await expect(page.getByLabel("Discount amount", { exact: true })).toBeDisabled()
  await expect(page.getByRole("button", { name: "Save new version", exact: true })).toBeDisabled()
  await page.getByRole("link", { name: "Edit the latest version", exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByLabel("Discount amount", { exact: true })).toBeEnabled()
  await page.getByRole("region", { name: "Instalment schedule" }).screenshot({ path: info.outputPath("instalments-mobile.png") })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy()
  await page.goto("/crm/configuration/quotation-templates")
  await expect(page.getByRole("link", { name, exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("templates-mobile.png"), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto("/crm/quotations")
  await expect(page.getByRole("heading", { name: "Quotations", exact: true })).toBeVisible()
  await expect(page.getByRole("navigation", { name: "CRM", exact: true })).toHaveCount(0)
  for (const section of ["CRM", "Contacts", "Activities", "Sales Documents", "Real Estate"]) await expect(page.getByRole("button", { name: section, exact: true })).toBeVisible()
  await expect(page.getByRole("textbox", { name: "Search quotations", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "CRM", exact: true }).click()
  await expect(page.getByRole("link", { name: "Projects", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Real Estate", exact: true }).click()
  await expect(page.getByRole("link", { name: "Projects", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("module-navigation-desktop.png"), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("button", { name: "Toggle Sidebar", exact: true }).first().click()
  await expect(page.getByRole("button", { name: "Sales Documents", exact: true })).toBeVisible()
  await page.getByRole("dialog").evaluate(async element => { await Promise.all(element.getAnimations({ subtree: true }).map(animation => animation.finished)) })
  await page.screenshot({ path: info.outputPath("module-navigation-mobile.png"), fullPage: true })
  await page.keyboard.press("Escape")
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto("/settings/modules")
  const moduleCard = (title: string) => page.getByRole("heading", { name: new RegExp(`^${title} -`) }).locator("../..")
  await expect(moduleCard("Sales Documents").getByRole("button", { name: "Disable", exact: true })).toBeDisabled()
  await moduleCard("Payment Plans").getByRole("button", { name: "Disable", exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Disable module", exact: true }).click()
  await expect(moduleCard("Payment Plans")).toContainText("Disabled")
  await page.screenshot({ path: info.outputPath("module-settings.png"), fullPage: true })
  await page.goto(`/crm/quotations/${quotationId}`)
  await expect(page.getByText("Payment Plans is disabled.", { exact: false })).toBeVisible()
  await expect(page.getByRole("button", { name: "Save new version", exact: true })).toBeDisabled()
  expect((await request.get(`/api/crm/quotations/${quotationId}/pdf?revision=1`)).status()).toBe(200)
  await page.goto(`/crm/quotations/new?opportunityId=${deal.id}`)
  await expect(page.getByRole("heading", { name: "New quotation", exact: true })).toBeVisible()
  await expect(page.getByRole("region", { name: "Instalment schedule", exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Save document", exact: true }).click()
  await expect(page).toHaveURL(/\/crm\/quotations\/(?!new)[^/?]+$/)
  const simpleId = page.url().split("/").at(-1)!
  expect((await (await request.get(`/api/crm/quotations/${simpleId}`)).json()).snapshot.content.instalments).toEqual([])
  const simplePdf = await request.get(`/api/crm/quotations/${simpleId}/pdf`)
  expect(simplePdf.status()).toBe(200)
  await simplePdf.body().then(data => fs.writeFileSync(info.outputPath("quotation-only.pdf"), data))
  expect((await request.patch("/api/modules", { data: { key: "salesDocuments", enabled: false } })).ok()).toBeTruthy()
  await page.reload()
  await expect(page.getByRole("heading", { name: "Sales Documents is not enabled", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Sales Documents", exact: true })).toHaveCount(0)
  expect((await request.get(`/api/crm/quotations/${quotationId}/pdf`)).status()).toBe(403)
  expect((await request.patch("/api/modules", { data: { key: "salesDocuments", enabled: true } })).ok()).toBeTruthy()
  expect((await request.patch("/api/modules", { data: { key: "paymentPlans", enabled: true } })).ok()).toBeTruthy()

})
