import { test, expect, type Page } from "@playwright/test"

test.beforeEach(async ({ baseURL, request }) => {
  test.skip(process.env.CRM_BROWSER_LOCAL_WRITES !== "1" || baseURL !== "http://intake-upgrade-a.localhost:3001", "Requires the disposable local sales fixture.")
  expect((await request.patch("/api/modules", { data: { key: "realEstate", enabled: true } })).ok()).toBe(true)
})
async function choose(page: Page, label: string, option: string) {
  await page.getByLabel(label, { exact: true }).click()
  await page.getByRole("menuitemradio", { name: option, exact: true }).click()
}

test("project to qualified lead, conversion, site visit and won opportunity uses the shared CRM workflow", async ({ page, request }, info) => {
  test.setTimeout(180000)
  const suffix = Date.now(), projectName = `Park Sales ${suffix}`, childName = `East Wing ${suffix}`, title = `Family home ${suffix}`, pipelineName = `Property process ${suffix}`
  const projectResponse = await request.post("/api/real-estate/projects", { data: { name: projectName, code: `SALES-${suffix}`, location: "Pune", lifecycle: "SELLING" } })
  expect(projectResponse.ok()).toBe(true)
  const project = await projectResponse.json()
  const childResponse = await request.post("/api/real-estate/projects", { data: { name: childName, code: `SALES-${suffix}-1`, parentId: project.id } })
  expect(childResponse.ok()).toBe(true)
  const child = await childResponse.json()
  const pipelineCount = (await (await request.get("/api/crm/pipelines")).json()).total
  await page.goto(`/crm/projects/${project.id}`)
  await page.getByRole("tab", { name: "Sales", exact: true }).click()
  await page.getByRole("link", { name: "Create property sales pipeline", exact: true }).click()
  await expect(page.getByLabel("Pipeline name", { exact: true })).toHaveValue("Property sales")
  await expect(page.getByLabel("Name", { exact: true }).nth(1)).toHaveValue("Site visit planned")
  expect((await (await request.get("/api/crm/pipelines")).json()).total).toBe(pipelineCount)
  await page.getByLabel("Pipeline name", { exact: true }).fill(pipelineName)
  await page.getByRole("button", { name: "Save pipeline", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Configure pipeline", exact: true })).toBeVisible()
  const pipelineId = new URL(page.url()).pathname.split("/").at(-1)!
  expect((await (await request.get("/api/crm/pipelines")).json()).total).toBe(pipelineCount + 1)
  await page.goto(`/crm/projects/${child.id}`)
  await page.getByRole("tab", { name: "Sales", exact: true }).click()
  await page.getByRole("link", { name: "New lead", exact: true }).click()
  await expect(page.getByLabel("Project (optional)", { exact: true })).toContainText(projectName)
  await expect(page.getByLabel("Subproject (optional)", { exact: true })).toContainText(childName)
  await choose(page, "Contact selection", "New contact")
  await page.getByLabel("Full name", { exact: true }).fill(`Buyer ${suffix}`)
  await page.getByLabel("Email", { exact: true }).fill(`buyer-${suffix}@example.test`)
  await page.getByLabel("Enquiry title", { exact: true }).fill(title)
  await page.getByLabel("Target close date (optional)", { exact: true }).fill("2026-12-15")
  await page.getByLabel("Minimum budget", { exact: true }).fill("7500000")
  await page.getByLabel("Maximum budget", { exact: true }).fill("9500000")
  await page.getByLabel("Budget currency (e.g. INR)", { exact: true }).fill("INR")
  await page.getByLabel("Bedrooms (0 for studio)", { exact: true }).fill("2")
  await page.getByLabel("Preferred property category", { exact: true }).click()
  await page.getByRole("option", { name: "Apartment", exact: true }).click()
  await page.screenshot({ path: info.outputPath("sales-lead-desktop.png"), fullPage: true })
  await page.getByRole("button", { name: "Save enquiry", exact: true }).click()
  await expect(page.getByRole("link", { name: "Convert to opportunity", exact: true })).toBeVisible()
  const leadId = new URL(page.url()).pathname.split("/").at(-1)!
  await choose(page, "Status", "QUALIFIED")
  await page.getByRole("button", { name: "Save enquiry", exact: true }).click()
  await expect.poll(async () => (await (await request.get(`/api/crm/enquiries/${leadId}`)).json()).status).toBe("QUALIFIED")
  await page.getByRole("link", { name: "Convert to opportunity", exact: true }).click()
  await expect(page.getByLabel("Expected close date", { exact: true })).toHaveValue("2026-12-15")
  await expect(page.getByLabel("Project (optional)", { exact: true })).toBeDisabled()
  await expect(page.getByLabel("Minimum budget", { exact: true })).toHaveValue("7500000")
  await page.getByLabel("Pipeline", { exact: true }).click()
  await page.getByRole("option", { name: pipelineName, exact: true }).click()
  await expect(page.getByLabel("Stage", { exact: true })).toContainText("Qualified interest")
  // Reselecting the current pipeline must preserve its selected stage.
  await page.getByLabel("Pipeline", { exact: true }).click()
  await page.getByRole("option", { name: pipelineName, exact: true }).click()
  await expect(page.getByLabel("Stage", { exact: true })).toContainText("Qualified interest")
  await page.getByLabel("Expected value", { exact: true }).fill("8000000")
  await page.getByRole("button", { name: "Save opportunity", exact: true }).click()
  await expect(page.getByRole("link", { name: "Schedule activity", exact: true })).toBeVisible()
  const dealId = new URL(page.url()).pathname.split("/").at(-1)!
  const deal = await (await request.get(`/api/crm/opportunities/${dealId}`)).json()
  expect(deal.propertyContext).toMatchObject({ projectId: project.id, subprojectId: child.id, bedrooms: 2, budgetCurrency: "INR" })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => { document.documentElement.classList.add("dark") })
  await page.screenshot({ path: info.outputPath("sales-opportunity-mobile-dark.png"), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole("link", { name: "Schedule activity", exact: true }).click()
  await page.getByLabel("Activity title", { exact: true }).fill(`Site visit ${suffix}`)
  await page.getByRole("combobox", { name: "Activity type", exact: true }).click()
  await page.getByRole("option", { name: "Meeting", exact: true }).click()
  await page.getByLabel("Due date", { exact: true }).fill("2026-10-01")
  await page.getByRole("button", { name: "Save activity", exact: true }).click()
  await expect(page.getByRole("heading", { name: `Site visit ${suffix}`, exact: true })).toBeVisible()
  await choose(page, "Outcome", "HELD")
  await page.getByLabel("Customer interaction summary", { exact: true }).fill("Buyer viewed East Wing and accepted the proposal.")
  await page.getByRole("button", { name: "Complete activity", exact: true }).click()
  await expect(page.getByText("COMPLETED", { exact: true })).toBeVisible()
  await page.goto(`/crm/opportunities/${dealId}`)
  await choose(page, "Stage", "Won")
  await page.getByRole("button", { name: "Save opportunity", exact: true }).click()
  await expect.poll(async () => (await (await request.get(`/api/crm/opportunities/${dealId}`)).json()).stage.kind).toBe("WON")
  await page.goto(`/crm/projects/${child.id}`)
  await page.getByRole("tab", { name: "Sales", exact: true }).click()
  await expect(page.getByRole("link", { name: title, exact: true })).toHaveCount(2)
  await page.getByRole("tab", { name: "Activities", exact: true }).click()
  await expect(page.getByRole("link", { name: `Site visit ${suffix}`, exact: true })).toBeVisible()
  await page.evaluate(() => { document.documentElement.classList.add("dark") })
  await expect(page.locator("html")).toHaveClass(/dark/)
  await page.screenshot({ path: info.outputPath("project-sales-desktop-dark.png"), fullPage: true })
  await page.evaluate(() => { document.documentElement.classList.remove("dark") })
  await page.screenshot({ path: info.outputPath("project-sales-desktop-light.png"), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath("project-sales-mobile-light.png"), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  // Matching list and board filters use the same query and retain the chosen project.
  await page.goto("/crm/opportunities")
  await page.getByLabel("Pipeline", { exact: true }).click()
  await page.getByRole("option", { name: pipelineName, exact: true }).click()
  await page.getByRole("button", { name: "Filters", exact: true }).click()
  await page.getByLabel("Project", { exact: true }).click()
  await page.getByRole("option", { name: projectName, exact: true }).click()
  await page.getByLabel("Subproject", { exact: true }).click()
  await page.getByRole("option", { name: childName, exact: true }).click()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("link", { name: title, exact: true })).toBeVisible()
  await page.getByRole("button", { name: "List", exact: true }).click()
  await expect(page.getByRole("link", { name: title, exact: true })).toBeVisible()
  const filtered = await request.get(`/api/crm/opportunities?pipelineId=${pipelineId}&projectId=${project.id}&subprojectId=${child.id}`)
  expect((await filtered.json()).total).toBe(1)
})

test("standalone project opportunities retain context through module-off editing and archived selections", async ({ page, request }, info) => {
  const suffix = Date.now(), title = `Standalone sale ${suffix}`, projectName = `Retained project ${suffix}`
  const projectResponse = await request.post("/api/real-estate/projects", { data: { name: projectName, code: `RETAIN-${suffix}` } })
  expect(projectResponse.ok()).toBe(true)
  const project = await projectResponse.json()
  const contactResponse = await request.post("/api/crm/contacts", { data: { name: `Existing buyer ${suffix}` } })
  expect(contactResponse.ok()).toBe(true)
  const contact = await contactResponse.json()
  await page.goto(`/crm/projects/${project.id}`)
  await page.getByRole("tab", { name: "Sales", exact: true }).click()
  await page.getByRole("link", { name: "New opportunity", exact: true }).click()
  await expect(page.getByLabel("Project (optional)", { exact: true })).toContainText(projectName)
  await page.getByLabel("Opportunity title", { exact: true }).fill(title)
  await page.getByLabel("Contact", { exact: true }).click()
  await page.getByRole("option", { name: contact.name, exact: true }).click()
  await page.getByLabel("Expected close date", { exact: true }).fill("2026-12-10")
  await page.getByLabel("Minimum budget", { exact: true }).fill("500")
  await page.getByLabel("Maximum budget", { exact: true }).fill("100")
  await page.getByLabel("Budget currency (e.g. INR)", { exact: true }).fill("INR")
  await page.getByRole("button", { name: "Save opportunity", exact: true }).click()
  await expect(page.getByRole("alert").filter({ hasText: "Maximum budget" })).toBeVisible()
  expect((await (await request.get(`/api/crm/opportunities?projectId=${project.id}`)).json()).total).toBe(0)
  await page.getByLabel("Maximum budget", { exact: true }).fill("1000")
  await page.getByRole("button", { name: "Save opportunity", exact: true }).click()
  await expect(page.getByRole("heading", { name: title, exact: true })).toBeVisible()
  const url = page.url(), dealId = new URL(url).pathname.split("/").at(-1)!
  expect((await request.patch("/api/modules", { data: { key: "realEstate", enabled: false } })).ok()).toBe(true)
  try {
    await page.reload()
    await expect(page.getByLabel("Opportunity title", { exact: true })).toHaveValue(title)
    await expect(page.getByRole("heading", { name: "Property interest", exact: true })).toHaveCount(0)
    await page.getByLabel("Opportunity title", { exact: true }).fill(`${title} edited`)
    await page.getByRole("button", { name: "Save opportunity", exact: true }).click()
    await expect.poll(async () => (await (await request.get(`/api/crm/opportunities/${dealId}`)).json()).title).toBe(`${title} edited`)
  } finally { expect((await request.patch("/api/modules", { data: { key: "realEstate", enabled: true } })).ok()).toBe(true) }
  // Archive through the normal versioned API, keeping the opportunity reference.
  const { name, code, version } = project
  expect((await request.patch(`/api/real-estate/projects/${project.id}`, { data: { name, code, version, archived: true } })).ok()).toBe(true)
  await page.reload()
  await expect(page.getByLabel("Project (optional)", { exact: true })).toContainText(`${projectName} (archived)`)
  await expect(page.getByLabel("Minimum budget", { exact: true })).toHaveValue("500")
  await page.getByLabel("Bedrooms (0 for studio)", { exact: true }).fill("3")
  await page.getByRole("button", { name: "Save opportunity", exact: true }).click()
  await expect.poll(async () => (await (await request.get(`/api/crm/opportunities/${dealId}`)).json()).propertyContext.bedrooms).toBe(3)
  await page.screenshot({ path: info.outputPath("archived-context-retained.png"), fullPage: true })
})
