import { test, expect } from "@playwright/test"

// Opt-in writes only against the disposable local fixture. Never runs on a
// hosted tenant or as part of the default read-only browser suite.
test.beforeEach(async ({ baseURL, request }) => {
  test.skip(process.env.CRM_BROWSER_LOCAL_WRITES !== "1" || baseURL !== "http://intake-upgrade-a.localhost:3001", "Requires the isolated local property fixture.")
  expect((await request.patch("/api/modules", { data: { key: "realEstate", enabled: true } })).ok()).toBe(true)
})

test("project sales catalogue supports creation, hierarchy, staff access and archive with standard layouts", async ({ page }, info) => {
  test.setTimeout(120000)
  await page.goto("/settings/modules")
  const moduleCard = page.locator("div.rounded-xl").filter({ has: page.getByRole("heading", { name: /^Real Estate/ }) })
  await expect(moduleCard.getByRole("heading")).toBeVisible()
  if (await moduleCard.getByRole("button", { name: "Enable", exact: true }).count()) await moduleCard.getByRole("button", { name: "Enable", exact: true }).click()
  await expect(moduleCard.getByRole("link", { name: "Open Real Estate" })).toBeVisible()
  await moduleCard.getByRole("link", { name: "Open Real Estate" }).click()
  await page.getByRole("link", { name: "New project", exact: true }).click()
  const code = `UI-${Date.now()}`
  await page.getByLabel("Project name", { exact: true }).fill("River Gardens")
  await page.getByLabel("Project code", { exact: true }).fill(code)
  await page.getByLabel("Location", { exact: true }).fill("Pune")
  await page.getByLabel("Indicative minimum price", { exact: true }).fill("7500000")
  await page.getByLabel("Indicative maximum price", { exact: true }).fill("9500000")
  await page.getByLabel("Currency code (e.g. INR)", { exact: true }).fill("INR")
  await page.getByLabel("Apartment", { exact: true }).check()
  await page.getByRole("button", { name: "Save project", exact: true }).click()
  await page.waitForURL(url => /\/crm\/projects\/[^/]+$/.test(url.pathname) && !url.pathname.endsWith("/new"))
  const parentUrl = page.url()
  await expect(page.getByRole("heading", { name: "River Gardens", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("project-desktop.png"), fullPage: true })
  await page.getByRole("link", { name: "New subproject", exact: true }).click()
  await expect(page.getByRole("heading", { name: "New subproject", exact: true })).toBeVisible()
  await page.getByLabel("Project name", { exact: true }).fill("Phase One")
  await page.getByLabel("Project code", { exact: true }).fill(`${code}-1`)
  await page.getByRole("button", { name: "Save project", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Phase One", exact: true })).toBeVisible()
  await expect(page.getByText("Staff access is inherited from the parent project.")).toBeVisible()
  await page.goto(parentUrl)
  await expect(page.getByRole("link", { name: "Phase One", exact: true })).toBeVisible()
  await page.getByLabel("Assign staff", { exact: true }).click()
  await page.getByRole("option").filter({ hasText: "Upgrade A" }).click()
  await page.getByRole("button", { name: "Add staff", exact: true }).click()
  await expect(page.getByRole("button", { name: "Remove Upgrade A", exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath("project-mobile.png"), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  await page.getByLabel("Record status", { exact: true }).click()
  await page.getByRole("menuitemradio", { name: "Archived", exact: true }).click()
  await page.getByRole("button", { name: "Save project", exact: true }).click()
  await expect(page.getByRole("dialog")).toBeVisible()
  await page.getByRole("button", { name: "Confirm and save", exact: true }).click()
  await expect(page.getByRole("button", { name: "Add staff", exact: true })).toHaveCount(0)
  await page.getByLabel("Record status", { exact: true }).click()
  await page.getByRole("menuitemradio", { name: "Active", exact: true }).click()
  await page.getByRole("button", { name: "Save project", exact: true }).click()
  await page.getByRole("button", { name: "Confirm and save", exact: true }).click()
  await expect(page.getByRole("button", { name: "Remove Upgrade A", exact: true })).toBeVisible()
})

test("staff read-only view and missing records do not expose edit controls", async ({ page }, info) => {
  const data = { id: "read-only", name: "Assigned project", code: "READ", location: "Pune", parentId: null, developerAccountId: null, description: "Sales context", categories: ["APARTMENT"], lifecycle: "SELLING", priceMin: "100", priceMax: "200", currency: "INR", archived: false, version: 1, canManage: false }
  await page.route("**/api/real-estate/projects**", route => {
    if (route.request().method() !== "GET") return route.abort()
    if (new URL(route.request().url()).pathname.endsWith("/read-only")) return route.fulfill({ json: data })
    return route.fulfill({ json: { items: [], total: 0, canManage: false, page: 1, pageSize: 20 } })
  })
  await page.goto("/crm/projects/read-only")
  await expect(page.getByRole("heading", { name: "Assigned project", exact: true })).toBeVisible()
  await expect(page.getByLabel("Project name", { exact: true })).toBeDisabled()
  await expect(page.getByRole("button", { name: "Save project", exact: true })).toHaveCount(0)
  await expect(page.getByRole("heading", { name: "Responsible staff and access" })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("project-readonly.png"), fullPage: true })
  await page.unroute("**/api/real-estate/projects**")
  await page.goto("/crm/projects/missing-project")
  await expect(page.getByRole("alert").filter({ hasText: "Project not found" })).toBeVisible()
  await expect(page.getByLabel("Project name", { exact: true })).toHaveCount(0)
})

test("module-off hides projects and preserves generic CRM access", async ({ page }) => {
  await page.goto("/settings/modules")
  const moduleCard = page.locator("div.rounded-xl").filter({ has: page.getByRole("heading", { name: /^Real Estate/ }) })
  await moduleCard.getByRole("button", { name: "Disable", exact: true }).click()
  await page.getByRole("button", { name: "Disable module", exact: true }).click()
  await expect(moduleCard.getByRole("button", { name: "Enable", exact: true })).toBeVisible()
  await page.goto("/crm/projects")
  await expect(page.getByRole("heading", { name: "Real Estate is not enabled", exact: true })).toBeVisible()
  expect((await page.request.get("/api/real-estate/projects")).status()).toBe(403)
  await page.goto("/crm/contacts")
  await expect(page.getByRole("heading", { name: "Contacts", exact: true })).toBeVisible()
  await page.goto("/settings/modules")
  await moduleCard.getByRole("button", { name: "Enable", exact: true }).click()
  await expect(moduleCard.getByRole("link", { name: "Open Real Estate" })).toBeVisible()
})
