/* eslint-disable @typescript-eslint/no-require-imports */
const { test, before, after } = require("node:test")
const assert = require("node:assert/strict")
const { randomUUID } = require("node:crypto")
const { Pool } = require("pg")
const { PrismaClient } = require("@prisma/client")
const { TenantPgAdapter } = require("../lib/tenant-pg-adapter.ts")
const { createRealEstateService } = require("../modules/real-estate/service.ts")
const { createCrmService } = require("../modules/crm/service.ts")
const { updateBusinessModule } = require("../platform/module-service.ts")
require("../lib/logger.ts").logger.info = () => {}
const raw = process.env.CRM_TEST_DATABASE_URL
if (!raw) throw new Error("CRM_TEST_DATABASE_URL is required.")
const url = new URL(raw)
if (!["127.0.0.1", "localhost"].includes(url.hostname) || url.pathname !== "/ls_salon_crm_test") throw new Error("Use only the dedicated local test database.")
const suffix = randomUUID().replaceAll("-", ""), a = `re_a_${suffix}`, b = `re_b_${suffix}`
const clients = [], pools = []
function client(tenantId, root = false) {
  const connection = new URL(raw)
  if (!root) { connection.username = "crm_test_runtime"; connection.password = "" }
  const pool = new Pool({ connectionString: connection.toString(), max: 4, ...(!root ? { options: `-c app.tenant_id=${tenantId || ""} -c app.rls_bypass=off` } : {}) })
  pools.push(pool)
  const db = new PrismaClient({ adapter: new TenantPgAdapter(pool, { tenantId: tenantId || undefined, bypass: root }) }); clients.push(db); return db
}
const root = client(null, true), db = client(a), dbB = client(b), unscoped = client(null)
const status = value => error => error.status === value
let admin, manager, staff, other, outsider, adminB, service, reader, stranger, second, developer
const input = (code, extra = {}) => ({ name: `Project ${code}`, code, location: "Pune", categories: ["APARTMENT"], lifecycle: "SELLING", ...extra })
const update = (project, extra = {}) => ({ name: project.name, code: project.code, parentId: project.parentId || "", developerAccountId: project.developerAccountId || "", location: project.location, description: project.description, categories: project.categories, lifecycle: project.lifecycle, priceMin: project.priceMin?.toString() || "", priceMax: project.priceMax?.toString() || "", currency: project.currency || "", archived: project.archived, version: project.version, ...extra })
before(async () => {
  await root.tenant.createMany({ data: [{ id: a, slug: a, name: "Property A" }, { id: b, slug: b, name: "Property B" }] })
  const user = (tenantId, role, name) => root.user.create({ data: { tenantId, role, name, email: `${name}-${suffix}@example.test` } })
  admin = await user(a, "ADMIN", "admin"); manager = await user(a, "MANAGER", "manager"); staff = await user(a, "STAFF", "staff"); other = await user(a, "STAFF", "other"); outsider = await user(a, "CUSTOMER", "customer"); adminB = await user(b, "ADMIN", "admin-b")
  await root.tenantModule.createMany({ data: [a, b].flatMap(tenantId => [{ tenantId, key: "crm", enabled: true }, { tenantId, key: "realEstate", enabled: true }]) })
  service = createRealEstateService(db, { tenantId: a, userId: manager.id }); reader = createRealEstateService(db, { tenantId: a, userId: staff.id }); stranger = createRealEstateService(db, { tenantId: a, userId: other.id }); second = createRealEstateService(dbB, { tenantId: b, userId: adminB.id })
  developer = await root.crmAccount.create({ data: { tenantId: a, ownerUserId: manager.id, name: "Private developer" } })
})
after(async () => {
  await Promise.all(clients.map(item => item.$disconnect()))
  await Promise.all(pools.map(pool => pool.end()))
})

test("additive project migration leaves existing CRM identifiers, versions and dates unchanged", { skip: process.env.CRM_TEST_EXPECT_PROJECT_UPGRADE !== "1" }, async () => {
  const enquiry = await root.crmEnquiry.findUniqueOrThrow({ where: { id: "intake_lead_a1" } })
  const deal = await root.crmOpportunity.findUniqueOrThrow({ where: { id: "intake_deal" } })
  assert.equal(enquiry.version, 4); assert.equal(enquiry.source, "  Web   Site  ")
  assert.equal(enquiry.createdAt.toISOString(), "2026-01-01T00:00:00.000Z")
  assert.equal(enquiry.updatedAt.toISOString(), "2026-02-01T00:00:00.000Z")
  assert.equal(deal.enquiryId, enquiry.id); assert.equal(deal.contactId, enquiry.contactId)
  assert.equal(deal.amount.toString(), "100"); assert.equal(deal.expectedCloseOn.toISOString(), "2026-12-01T00:00:00.000Z")
  assert.equal(await root.realEstateProject.count({ where: { id: { in: [enquiry.id, deal.id, enquiry.contactId] } } }), 0)
})

test("projects, subprojects and members are scoped; memberships do not expose private developer accounts", async () => {
  let parent = await service.createProject(input("SCOPE", { developerAccountId: developer.id, priceMin: "100.1234", priceMax: "999.99", currency: "INR" }))
  const child = await service.createProject(input("SCOPE-1", { parentId: parent.id }))
  assert.equal((await reader.listProjects({})).total, 0)
  await assert.rejects(reader.getProject(parent.id), status(404))
  parent = { ...parent, ...await service.changeMember(parent.id, { userId: staff.id, version: parent.version }) }
  assert.equal((await reader.listProjects({})).total, 1)
  assert.equal((await reader.listProjects({ parentId: parent.id })).items[0].id, child.id)
  const visible = await reader.getProject(parent.id)
  assert.equal(visible.developerAccountId, null); assert.equal(visible.developerRestricted, true)
  assert.equal((await reader.getProject(child.id)).parent.id, parent.id)
  await assert.rejects(reader.listMembers(parent.id, {}), status(403))
  await assert.rejects(reader.createProject(input("STAFF")), status(403))
  await assert.rejects(reader.updateProject(parent.id, update(parent)), status(403))
  await assert.rejects(stranger.getProject(child.id), status(404))
  await assert.rejects(second.getProject(parent.id), status(404))
  assert.equal((await service.listMembers(parent.id, {})).items[0].id, staff.id)
  await service.changeMember(parent.id, { userId: staff.id, version: parent.version, remove: true })
  await assert.rejects(reader.getProject(child.id), status(404))
  assert.equal(await unscoped.realEstateProject.count(), 0)
  assert.equal(await dbB.realEstateProject.count({ where: { tenantId: a } }), 0)
  assert.equal(await dbB.realEstateProjectMember.count({ where: { tenantId: a } }), 0)
})
test("validates hierarchy, codes, prices and tenant-safe developer/staff relationships", async () => {
  const parent = await service.createProject(input(" code-one "))
  assert.equal(parent.code, "CODE-ONE")
  const child = await service.createProject(input("CODE-TWO", { parentId: parent.id }))
  await assert.rejects(service.createProject(input("code-one")), status(409))
  await assert.rejects(service.createProject(input("DEPTH", { parentId: child.id })), status(400))
  await assert.rejects(service.updateProject(child.id, update(child, { parentId: "" })), status(400))
  await assert.rejects(second.createProject(input("BAD-PARENT", { parentId: parent.id })), status(400))
  await assert.rejects(second.createProject(input("BAD-DEVELOPER", { developerAccountId: developer.id })), status(400))
  await assert.rejects(service.createProject(input("BAD-PRICE", { priceMin: "10", priceMax: "5", currency: "INR" })), status(400))
  await assert.rejects(service.createProject(input("NO-CURRENCY", { priceMin: "10" })), status(400))
  await assert.rejects(service.changeMember(parent.id, { userId: adminB.id, version: 1 }), status(400))
  await assert.rejects(service.changeMember(parent.id, { userId: outsider.id, version: 1 }), status(400))
  await assert.rejects(service.changeMember(child.id, { userId: staff.id, version: 1 }), status(409))
  await assert.rejects(root.realEstateProject.create({ data: { tenantId: b, name: "Foreign", code: "FOREIGN", parentId: parent.id } }), error => error.code === "P2003")
  await assert.rejects(root.realEstateProjectMember.create({ data: { tenantId: a, projectId: parent.id, userId: adminB.id } }), error => error.code === "P2003")
  await assert.rejects(root.realEstateProject.create({ data: { tenantId: b, name: "Foreign", code: "FOREIGN", developerAccountId: developer.id } }), error => error.code === "P2003")
})
test("archive and restore preserve child state and memberships while blocking staff reads", async () => {
  let parent = await service.createProject(input("ARCHIVE"))
  let child = await service.createProject(input("ARCHIVE-1", { parentId: parent.id }))
  parent = { ...parent, ...await service.changeMember(parent.id, { userId: staff.id, version: 1 }) }
  child = await service.updateProject(child.id, update(child, { archived: true }))
  parent = await service.updateProject(parent.id, update(parent, { archived: true }))
  await assert.rejects(reader.getProject(parent.id), status(404))
  await assert.rejects(service.createProject(input("ARCHIVE-2", { parentId: parent.id })), status(409))
  await assert.rejects(service.updateProject(child.id, update(child, { archived: false })), status(409))
  parent = await service.updateProject(parent.id, update(parent, { archived: false }))
  assert.equal((await reader.getProject(parent.id)).id, parent.id)
  await assert.rejects(reader.getProject(child.id), status(404))
  await service.updateProject(child.id, update(child, { archived: false }))
  assert.equal((await reader.getProject(child.id)).id, child.id)
})
test("optimistic versions prevent stale edits and membership changes; audits commit atomically", async () => {
  let project = await service.createProject(input("VERSION"))
  const original = project
  project = await service.updateProject(project.id, update(project, { name: "Changed" }))
  await assert.rejects(service.updateProject(project.id, update(original)), status(409))
  await assert.rejects(service.changeMember(project.id, { userId: staff.id, version: 1 }), status(409))
  const results = await Promise.allSettled([service.updateProject(project.id, update(project, { location: "A" })), service.updateProject(project.id, update(project, { location: "B" }))])
  assert.equal(results.filter(item => item.status === "fulfilled").length, 1)
  const events = await root.auditLog.findMany({ where: { tenantId: a, entityId: project.id }, orderBy: { createdAt: "asc" } })
  assert.deepEqual(events.map(row => row.event), ["realEstate.project.created", "realEstate.project.updated", "realEstate.project.updated"])
  const broken = new Proxy(db, { get(target, prop) { if (prop !== "$transaction") return Reflect.get(target, prop); return (operation, options) => target.$transaction(tx => operation(new Proxy(tx, { get(inner, key) { return key === "auditLog" ? { create: async () => { throw new Error("audit unavailable") } } : Reflect.get(inner, key) } })), options) } })
  await assert.rejects(createRealEstateService(broken, { tenantId: a, userId: admin.id }).createProject(input("ROLLBACK")), /audit unavailable/)
  assert.equal(await root.realEstateProject.count({ where: { tenantId: a, code: "ROLLBACK" } }), 0)
})
test("search and pagination remain server-side and archived choices are separate", async () => {
  for (let i = 0; i < 3; i++) await service.createProject(input(`SEARCH-${i}`, { name: `Searchable ${i}`, location: "Chennai" }))
  const first = await service.listProjects({ q: "Chennai", pageSize: 2 })
  const next = await service.listProjects({ q: "Chennai", pageSize: 2, page: 2 })
  assert.equal(first.total, 3); assert.equal(first.items.length, 2); assert.equal(next.items.length, 1)
  assert.ok(!first.items.some(row => row.id === next.items[0].id))
  assert.equal((await service.listProjects({ q: "SEARCH-2", lifecycle: "SELLING" })).total, 1)
  assert.equal((await service.listProjects({ q: "SEARCH", lifecycle: "PLANNING" })).total, 0)
})
test("module dependency is atomic, admin-only and preserves CRM and property records", async () => {
  const identity = { tenantId: a, userId: admin.id }
  await assert.rejects(updateBusinessModule(db, { tenantId: a, userId: manager.id }, { key: "realEstate", enabled: false }), status(403))
  await assert.rejects(updateBusinessModule(db, identity, { key: "crm", enabled: false }), status(409))
  const count = await root.realEstateProject.count({ where: { tenantId: a } })
  await updateBusinessModule(db, identity, { key: "realEstate", enabled: false })
  await assert.rejects(service.listProjects({}), status(403))
  const crm = createCrmService(db, identity)
  const contact = await crm.createContact({ name: "Generic CRM still works" })
  assert.equal((await crm.getContact(contact.id)).name, contact.name)
  await updateBusinessModule(db, identity, { key: "crm", enabled: false })
  await assert.rejects(updateBusinessModule(db, identity, { key: "realEstate", enabled: true }), status(409))
  await updateBusinessModule(db, identity, { key: "crm", enabled: true })
  const races = await Promise.allSettled([updateBusinessModule(db, identity, { key: "realEstate", enabled: true }), updateBusinessModule(db, identity, { key: "crm", enabled: false })])
  assert.ok(races.some(result => result.status === "rejected"))
  const flags = await root.tenantModule.findMany({ where: { tenantId: a } })
  assert.ok(!flags.find(row => row.key === "realEstate").enabled || flags.find(row => row.key === "crm").enabled)
  await updateBusinessModule(db, identity, { key: "crm", enabled: true })
  await updateBusinessModule(db, identity, { key: "realEstate", enabled: true })
  assert.equal(await root.realEstateProject.count({ where: { tenantId: a } }), count)
})
test("permissions recheck current user and tenant state", async () => {
  await root.user.update({ where: { id: manager.id }, data: { status: "SUSPENDED" } })
  await assert.rejects(service.listProjects({}), status(403))
  await root.user.update({ where: { id: manager.id }, data: { status: "ACTIVE", role: "STAFF" } })
  await assert.rejects(service.createProject(input("DEMOTED")), status(403))
  await root.user.update({ where: { id: manager.id }, data: { role: "MANAGER" } })
  await root.tenant.update({ where: { id: a }, data: { status: "SUSPENDED" } })
  await assert.rejects(service.listProjects({}), status(403))
  await root.tenant.update({ where: { id: a }, data: { status: "ACTIVE" } })
})
const { propertySalesPipeline } = require("../modules/real-estate/pipeline-template.ts")
const crmManager = () => createCrmService(db, { tenantId: a, userId: manager.id })
const crmStaff = () => createCrmService(db, { tenantId: a, userId: staff.id })
const leadEdit = (lead, extra = {}) => ({ title: lead.title, assignedUserId: lead.assignedUserId, status: lead.status, version: lead.version, requirements: lead.requirements || "", ...extra })
const dealEdit = (deal, extra = {}) => ({ title: deal.title, pipelineId: deal.pipelineId, stageId: deal.stageId, contactId: deal.contactId, accountId: deal.accountId || "", assignedUserId: deal.assignedUserId, amount: String(deal.amount), currency: deal.currency, expectedCloseOn: deal.expectedCloseOn.toISOString().slice(0,10), version: deal.version, ...extra })
async function salesFixture(code, owner = manager) {
  const crm = crmManager(), project = await service.createProject(input(code)), subproject = await service.createProject(input(`${code}-1`, { parentId: project.id }))
  const contact = await crm.createContact({ name: `Buyer ${code}` })
  const lead = await crm.createEnquiry({ title: `Lead ${code}`, contactId: contact.id, assignedUserId: owner.id, targetCloseOn: "2026-12-12", propertyContext: { projectId: project.id, subprojectId: subproject.id, budgetMin: "100.125", budgetMax: "200", budgetCurrency: "INR", bedrooms: 2, propertyCategory: "APARTMENT", buyingTimeframe: "WITHIN_3_MONTHS" } })
  const pipeline = await crm.createPipeline({ ...structuredClone(propertySalesPipeline), name: `Pipeline ${code}` })
  const conversion = { title: `Deal ${code}`, pipelineId: pipeline.id, stageId: pipeline.stages[0].id, contactId: contact.id, assignedUserId: owner.id, amount: "150", currency: "INR", enquiryId: lead.id, enquiryVersion: lead.version }
  return { crm, project, subproject, contact, lead, pipeline, conversion }
}

test("sales context validates selected project hierarchy, membership, budgets and atomic inline contact rollback", async () => {
  const f = await salesFixture("SALES-VALID")
  const unrelated = await service.createProject(input("SALES-OTHER"))
  const foreign = await second.createProject(input("SALES-FOREIGN"))
  const make = context => f.crm.createEnquiry({ title: "Invalid project lead", assignedUserId: manager.id, newContact: { name: "Must roll back", email: `rollback-${suffix}@example.test` }, propertyContext: context })
  for (const context of [{ projectId: foreign.id }, { projectId: f.subproject.id }, { projectId: unrelated.id, subprojectId: f.subproject.id }, { budgetMin: "50", budgetMax: "10", budgetCurrency: "INR" }, { budgetMin: "10" }]) await assert.rejects(make(context), status(400))
  assert.equal(await root.crmContact.count({ where: { tenantId: a, email: `rollback-${suffix}@example.test` } }), 0)
  const staffContact = await crmStaff().createContact({ name: "Staff buyer" })
  await assert.rejects(crmStaff().createEnquiry({ title: "Not a member", contactId: staffContact.id, assignedUserId: staff.id, propertyContext: { projectId: f.project.id } }), status(400))
  await service.changeMember(f.project.id, { userId: staff.id, version: f.project.version })
  assert.equal((await crmStaff().createEnquiry({ title: "Member lead", contactId: staffContact.id, assignedUserId: staff.id, propertyContext: { projectId: f.project.id, subprojectId: f.subproject.id } })).propertyContext.subprojectId, f.subproject.id)
  const fresh = await service.getProject(f.project.id)
  await service.updateProject(f.project.id, update(fresh, { archived: true }))
  await assert.rejects(make({ projectId: f.project.id }), status(400))
})

test("omitted fields preserve context, explicit clearing is versioned and reassignment does not grant project access", async () => {
  const f = await salesFixture("SALES-EDIT")
  let lead = await f.crm.updateEnquiry(f.lead.id, leadEdit(f.lead, { assignedUserId: staff.id }))
  assert.equal(lead.propertyContext.subprojectId, f.subproject.id)
  await assert.rejects(reader.getProject(f.project.id), status(404))
  assert.equal((await crmStaff().getEnquiry(lead.id)).propertyContext.project.name, f.project.name)
  const choices = await crmStaff().listProjectFilterChoices({ q: f.project.name })
  assert.equal(choices.items[0].id, f.project.id)
  assert.equal(choices.items[0].developerAccountId, undefined)
  await assert.rejects(crmStaff().updateEnquiry(lead.id, leadEdit(f.lead, { assignedUserId: staff.id, propertyContext: null })), status(409))
  assert.equal((await crmStaff().getEnquiry(lead.id)).propertyContext.projectId, f.project.id)
  await service.updateProject(f.project.id, update(f.project, { archived: true }))
  lead = await crmStaff().updateEnquiry(lead.id, leadEdit(lead, { propertyContext: { projectId: f.project.id, budgetMax: "300", budgetCurrency: "INR" } }))
  assert.equal(lead.propertyContext.project.archived, true)
  assert.equal(lead.propertyContext.subprojectId, null)
  lead = await crmStaff().updateEnquiry(lead.id, leadEdit(lead, { propertyContext: null }))
  assert.equal(lead.propertyContext, null)
  assert.equal((await crmStaff().listProjectFilterChoices({ q: f.project.name })).total, 0)
})

test("conversion copies current requirements and target date once; opportunity changes are independent", async () => {
  const f = await salesFixture("SALES-CONVERT")
  const lead = await f.crm.updateEnquiry(f.lead.id, leadEdit(f.lead, { status: "QUALIFIED", propertyContext: { projectId: f.project.id, subprojectId: f.subproject.id, budgetMin: "250", budgetCurrency: "INR", bedrooms: 3 } }))
  await assert.rejects(f.crm.createOpportunity(f.conversion), status(409))
  const requests = await Promise.all([f.crm.createOpportunity({ ...f.conversion, enquiryVersion: lead.version }), f.crm.createOpportunity({ ...f.conversion, enquiryVersion: lead.version })])
  assert.equal(requests[0].id, requests[1].id)
  let deal = requests[0]
  assert.equal(deal.propertyContext.budgetMin.toString(), "250")
  assert.equal(deal.expectedCloseOn.toISOString().slice(0,10), "2026-12-12")
  assert.equal(await root.realEstateOpportunityContext.count({ where: { tenantId: a, opportunityId: deal.id } }), 1)
  assert.equal(await root.auditLog.count({ where: { tenantId: a, entityId: deal.id, event: "realEstate.opportunity.context.copied" } }), 1)
  deal = await f.crm.updateOpportunity(deal.id, dealEdit(deal, { propertyContext: { projectId: f.project.id, bedrooms: 4 } }))
  assert.equal(deal.propertyContext.bedrooms, 4)
  assert.equal((await f.crm.getEnquiry(lead.id)).propertyContext.bedrooms, 3)
  assert.equal((await f.crm.createOpportunity(f.conversion)).propertyContext.bedrooms, 4)
})

test("disabled module hides context without deleting it and conversion retains archived references", async () => {
  const f = await salesFixture("SALES-OFF")
  await service.updateProject(f.project.id, update(f.project, { archived: true }))
  const identity = { tenantId: a, userId: admin.id }
  await updateBusinessModule(db, identity, { key: "realEstate", enabled: false })
  try {
    assert.equal((await f.crm.getEnquiry(f.lead.id)).propertyContext, null)
    const edited = await f.crm.updateEnquiry(f.lead.id, leadEdit(f.lead, { title: "Generic edit" }))
    await assert.rejects(f.crm.updateEnquiry(edited.id, leadEdit(edited, { propertyContext: null })), status(403))
    await assert.rejects(f.crm.listEnquiries({ projectId: f.project.id }), status(403))
    const deal = await f.crm.createOpportunity({ ...f.conversion, enquiryVersion: edited.version })
    assert.equal(deal.propertyContext, null)
    assert.equal((await root.realEstateOpportunityContext.findUnique({ where: { tenantId_opportunityId: { tenantId: a, opportunityId: deal.id } } })).subprojectId, f.subproject.id)
    await updateBusinessModule(db, identity, { key: "realEstate", enabled: true })
    assert.equal((await f.crm.getOpportunity(deal.id)).propertyContext.project.archived, true)
  } finally { await updateBusinessModule(db, identity, { key: "realEstate", enabled: true }) }
})

test("project filters paginate accessible records and delegated work cannot disclose a private parent project", async () => {
  const f = await salesFixture("SALES-FILTER", staff)
  const deal = await f.crm.createOpportunity(f.conversion)
  const privateLead = await f.crm.createEnquiry({ title: "Private lead", contactId: f.contact.id, assignedUserId: manager.id, propertyContext: { projectId: f.project.id } })
  await f.crm.createWork({ title: "Delegated private lead", type: "TASK", contactId: f.contact.id, enquiryId: privateLead.id, assignedUserId: staff.id, dueOn: "2026-10-01" })
  await f.crm.createWork({ title: "Accessible site visit", type: "MEETING", contactId: f.contact.id, opportunityId: deal.id, assignedUserId: staff.id, dueOn: "2026-10-01" })
  assert.equal((await f.crm.listEnquiries({ projectId: f.project.id, pageSize: 1 })).total, 2)
  const first = await f.crm.listEnquiries({ projectId: f.project.id, pageSize: 1 }), next = await f.crm.listEnquiries({ projectId: f.project.id, pageSize: 1, page: 2 })
  assert.notEqual(first.items[0].id, next.items[0].id)
  assert.equal((await crmStaff().listEnquiries({ projectId: f.project.id })).total, 1)
  assert.equal((await crmStaff().listEnquiries({ projectId: f.project.id, subprojectId: f.subproject.id })).total, 1)
  assert.equal((await crmStaff().listOpportunities({ projectId: f.project.id, pipelineId: f.pipeline.id, stageId: f.pipeline.stages[0].id })).items[0].id, deal.id)
  assert.equal((await crmStaff().listWork({ projectId: f.project.id, scope: "visible", state: "all" })).total, 1)
  assert.equal((await createCrmService(db, { tenantId: a, userId: other.id }).listEnquiries({ projectId: f.project.id })).total, 0)
  assert.equal((await createCrmService(dbB, { tenantId: b, userId: adminB.id }).listOpportunities({ projectId: f.project.id })).total, 0)
  await assert.rejects(f.crm.listEnquiries({ subprojectId: f.subproject.id }), status(400))
})

test("extension contexts enforce tenant RLS and composite parent-child constraints below the service", async () => {
  const f = await salesFixture("SALES-FK")
  const foreign = await second.createProject(input("SALES-FK-B"))
  await assert.rejects(root.realEstateEnquiryContext.update({ where: { tenantId_enquiryId: { tenantId: a, enquiryId: f.lead.id } }, data: { projectId: foreign.id, subprojectId: null } }), error => error.code === "P2003")
  const otherProject = await service.createProject(input("SALES-FK-OTHER"))
  await assert.rejects(root.realEstateEnquiryContext.update({ where: { tenantId_enquiryId: { tenantId: a, enquiryId: f.lead.id } }, data: { projectId: otherProject.id } }), error => error.code === "P2003")
  await assert.rejects(root.realEstateEnquiryContext.create({ data: { tenantId: b, enquiryId: f.lead.id, projectId: foreign.id } }), error => error.code === "P2003")
  await assert.rejects(root.realEstateEnquiryContext.update({ where: { tenantId_enquiryId: { tenantId: a, enquiryId: f.lead.id } }, data: { projectId: null } }))
  await assert.rejects(root.realEstateEnquiryContext.update({ where: { tenantId_enquiryId: { tenantId: a, enquiryId: f.lead.id } }, data: { budgetMax: "1" } }))
  await f.crm.createOpportunity(f.conversion)
  assert.equal(await unscoped.realEstateEnquiryContext.count(), 0)
  assert.equal(await dbB.realEstateEnquiryContext.count({ where: { tenantId: a } }), 0)
  assert.equal(await dbB.realEstateOpportunityContext.count({ where: { tenantId: a } }), 0)
})

test("failed context copy audit rolls back the entire opportunity conversion", async () => {
  const f = await salesFixture("SALES-ROLLBACK")
  const broken = new Proxy(db, { get(target, prop) { if (prop !== "$transaction") return Reflect.get(target, prop); return (operation, options) => target.$transaction(tx => operation(new Proxy(tx, { get(inner, key) { if (key !== "auditLog") return Reflect.get(inner, key); return { create: async args => { if (args.data.event === "realEstate.opportunity.context.copied") throw new Error("context audit unavailable"); return inner.auditLog.create(args) } } } })), options) } })
  await assert.rejects(createCrmService(broken, { tenantId: a, userId: manager.id }).createOpportunity(f.conversion), /context audit unavailable/)
  assert.equal(await root.crmOpportunity.count({ where: { tenantId: a, enquiryId: f.lead.id } }), 0)
  assert.equal(await root.crmActivity.count({ where: { tenantId: a, enquiryId: f.lead.id, event: "crm.enquiry.converted" } }), 0)
  assert.equal((await f.crm.createOpportunity(f.conversion)).propertyContext.projectId, f.project.id)
})

test("property pipeline is an explicit new draft and qualified sales flow reuses meetings, calls and won/lost stages", async () => {
  const f = await salesFixture("SALES-FLOW", staff)
  const before = await f.crm.getPipeline(f.pipeline.id)
  const custom = structuredClone(propertySalesPipeline); custom.name = "My property process"; custom.stages[0].name = "Buyer qualified"
  const newPipeline = await f.crm.createPipeline(custom)
  assert.notEqual(newPipeline.id, before.id)
  assert.deepEqual((await f.crm.getPipeline(before.id)).stages, before.stages)
  let lead = await crmStaff().updateEnquiry(f.lead.id, leadEdit(f.lead, { status: "QUALIFIED" }))
  let deal = await crmStaff().createOpportunity({ ...f.conversion, enquiryVersion: lead.version })
  const visit = await crmStaff().createWork({ title: "Site visit", type: "MEETING", contactId: f.contact.id, opportunityId: deal.id, assignedUserId: staff.id, dueOn: "2026-10-01" })
  await crmStaff().completeWork(visit.id, { version: visit.version, outcome: "HELD", summary: "Buyer viewed the property", occurredAt: new Date().toISOString(), followUp: { title: "Discuss proposal", type: "CALL", callDirection: "OUTBOUND", assignedUserId: staff.id, dueOn: "2026-10-02" } })
  const followUp = (await crmStaff().listWork({ projectId: f.project.id })).items[0]
  assert.equal(followUp.opportunityId, deal.id)
  await crmStaff().completeWork(followUp.id, { version: followUp.version, outcome: "CONNECTED", summary: "Proposal accepted", occurredAt: new Date().toISOString() })
  assert.equal((await crmStaff().getOpportunity(deal.id)).stageId, f.pipeline.stages[0].id)
  deal = await crmStaff().moveOpportunity(deal.id, { version: deal.version, pipelineId: f.pipeline.id, stageId: f.pipeline.stages.find(s => s.kind === "WON").id })
  assert.equal(deal.propertyContext.projectId, f.project.id)
  assert.equal(deal.stage.kind, "WON")
  deal = await crmStaff().moveOpportunity(deal.id, { version: deal.version, pipelineId: f.pipeline.id, stageId: f.pipeline.stages[0].id })
  await assert.rejects(crmStaff().moveOpportunity(deal.id, { version: deal.version, pipelineId: f.pipeline.id, stageId: f.pipeline.stages.find(s => s.kind === "LOST").id }), status(400))
  deal = await crmStaff().moveOpportunity(deal.id, { version: deal.version, pipelineId: f.pipeline.id, stageId: f.pipeline.stages.find(s => s.kind === "LOST").id, lossReason: "Buyer deferred purchase" })
  assert.equal(deal.stage.kind, "LOST")
  assert.equal(deal.propertyContext.projectId, f.project.id)
})
